INSERT INTO Author (name) VALUES
	(Brockbank, A.,),
	(Morata, López, N., & Cols),
	(Font, C.M., Mir, E.B., Badia, M.C.),
	(Devoe, P. H.),
	(Núñez, J. C., Solano, P., Antonio, J., & Pedro, G.),
	(Kane, J. W., & Sternheim, M. M.),
	(López, N., & y Cols.),
	(Aurengo, A., & Petitclerc, T.),
	(Bushong, S.),
	(Cromer, A.),
	(Davidovits, P.),
	(Frumento, A.),
	(Galle, P., & Paulin, R.),
	(Jou Mirabent, D.),
	(Mohammed, A. M.),
	(Chang, Raymond; Goldsby, Ken),
	(Bailey, P. S., & Bailey, C. A.),
	(McMurry, J.),
	(Santamaría, F.),
	(Petrucci, R. H., Harwood, W. S., Herring, F. G., & Pardo, C.),
	(Mahan, B. H., de Banchero, G. Y., & de Herold, L. P. E.),
	(Morrison, R. T., & Boyd, R. N.),
	(Sandler. TW.),
	(Moore et al.),
	(Moore y Dalley.),
	(Schünke et al.),
	(Drake et al.),
	(Federative Committe on Anatomical Terminology.),
	(Guzmán, L. et al.),
	(Pró E.),
	(Rouvière & Delmas.),
	(Anne M. Gilroy et al.),
	(Frank H. Netter),
	(Paulsen y Waschke),
	(Platzer W.),
	(Rohen et al.),
	(Ryan et al.),
	(Weber et al.),
	(Weir y Abrahams),
	(Alberts et al.),
	(Chandar & Viselli.),
	(Berg et al.),
	(Alfonso Calvo),
	(Cooper & Hausman.),
	(Cox et al.),
	(Gersen & Keagle.),
	(Jorde et al.),
	(Lodish et al.),
	(Nelson & Cox),
	(Nussbaum et al.),
	(Pierce, BA.),
	(Pritchard & Korf),
	(Salazar Montes et al.),
	(Solari y Roubicek),
	(Watson et al.),
	(Hoffmann, L., Bradley, G., & Rosen, K.),
	(González Rosales, A.),
	(Larson, RE. Hostetler, RP. Edwars, BH),
	(Spivak, M),
	(Swokowski E. Cole J.),
	(Sánchez González, MA.),
	(Alder et al.),
	(Cruz-Coke Madrid R.),
	(Illanes MA.),
	(Illich, I.),
	(Jünger, E.),
	(Laín Entralgo, P.),
	(López Piñero & Terrada),
	(Porter, R.),
	(Riera J.),
	(Hall, J. E.),
	(West. J. B.),
	(Eaton, D. C., & Pooler, J.P.),
	(Barrett, K. E.),
	(Constanzo, L .S.),
	(Courneya, C. A. M., & Parker, M. J.),
	(Levitzky, M. G.),
	(Danziger, J., Zeidel, M., & Parker, M. J.),
	(Lodish, H.),
	(Voet, D. L.),
	(Berg, J. M., Tymoczko, J. L., & Stryer, L.),
	(Murray, R. K., Bender, D. A. Botham, K. M., Kennelly, P. J.),
	(Jorde, L. B., Carey, J. C., & Bamshad, M. J.),
	(Pierce, B. A.),
	(Pritchard, D., J., & Korf, B. R.),
	(Watson, J. D.),
	(Moore, K.L., Dalley),
	(Federative Committe on Anatomical Terminology),
	(Guzman, L. et al.),
	(Pró),
	(Cibanal J. et al.),
	(Ruiz M.),
	(Balzey-R.),
	(Cleries X.),
	(Cole & Bird),
	(Fortin et al.),
	(Gelabert A.),
	(Glendinning & Holmstrom),
	(Kurtz et al.),
	(McCorry & Mason),
	(Merayo P. et al.),
	(Molinuevo A.),
	(Novack, D.),
	(Watzawick P.),
	(Cunningham G., Redston),
	(Maris A., Soars L.),
	(Marks J.),
	(Murphy R.),
	(Alexander, L.G.),
	(Murphy J.),
	(Freer J.),
	(Jamieson et. Al),
	(Argente y Alvarez),
	(Barr D.),
	(Bickley, L.S.),
	(Cardellach et al.),
	(Douglas et al.),
	(Goic et al.),
	(Jandial & Jandial),
	(Valtueña, JMP),
	(Smeltzer et al.),
	(Sommers F.),
	(Sanchez, MA.),
	(Sapag-Hagar, M.),
	(Gracia, D.),
	(Ameneiros et al.),
	(Aristóteles),
	(Clavé E.),
	(Consejo General de los Colegios Oficiales de Médicos),
	(Couceiro A.),
	(Drane, J.),
	(Gómez, J.),
	(Herranz, G.),
	(Lolas, F.),
	(Ministerio de Salud),
	(Santos de Unamuno, C.),
	(Hall, J.),
	(Johnson, L.),
	(Molina, P.),
	(Barrett, e.a.),
	(Barrett, K.),
	(Constanzo, L),
	(White, Bruce A., Porterfield, Susan P.),
	(Fortoul, Teresa),
	(Gartner - Hiatt),
	(Piezzine, R. & Fornes, M.),
	(Ross & Pawlina),
	(Kandel et al.),
	(Kierszenbaum & Tres),
	(Junqueira),
	(Paulsen, D.),
	(Welsch, U.),
	(Brüel. Christensen. Tranum-Jensen. Qvortrup. Geneser),
	(Montalvo, A.),
	(Boya, J.),
	(Martín-Lacave, I.),
	(Sobotta & cols),
	(Villaro, AC.),
	(Young et al.),
	(Ato, M.L.),
	(Bottasso, Oscar),
	(García, e.a.),
	(Narváez, D.),
	(Castañeda, JJ.),
	(Hernández Sampieri, Roberto),
	(Lemus, J.),
	(Ruiz, O.),
	(Soria-Aledo, V.),
	(Valles, M.),
	(Redston, Chris. Cunningham Gillie ),
	(John & Liz Soars),
	(Marks, Jonathan),
	(Murphy, Raymond),
	(Murphy, R. & Altman, R.),
	(Cortese, Elisa),
	(De la Fuente),
	(Florenzano, R. y Zegers, B.),
	(Ruiz Moral R.),
	(Thambirajah M.),
	(Coulehan),
	(Díaz Méndez, Darío y Latorre Postigo, José Miguel),
	(Fadem B.),
	(Gross R.),
	(Mosser & Begun),
	(Nolen-Hoeksema et al.),
	(Redolar D.),
	(Van Servellen, G.),
	(Gutierrez, I ),
	(Marañón, G.),
	(Pastrana, J.),
	(Buja, M.),
	(Edward, C. Klatt, R.),
	(Kemp, e.a.),
	(Kasper, e.a.),
	(Stefan Silbernagl, Florian Lang),
	(Laso Guzmán, F.),
	(López., R.),
	(McPhee., H.),
	(Sheila Grossman, Carol Mattson Porth),
	(Walker, e.a.),
	(Perez Arellano, J. L.),
	(Goljan, E.),
	(Kumar, e.a.),
	(Pardo, M.),
	(Reisner),
	(Strayer, David S. Rubin, Emanuel),
	(Rubin., S.),
	(Stevens, A.),
	(Arthur S. Schneider. Philip A.Szanto),
	(Bickley),
	(Mandell, J),
	(Argente & Alvarez),
	(Cardellach, L. et al.),
	(Casado, V. et al.),
	(Hampton, J.),
	(Herring, W.),
	(Houghton & Gray),
	(Kassirer et al.),
	(Laposata, M.),
	(Laso FJ.),
	(Leblond et al.),
	(McGee S.),
	(Pagana et al.),
	(Perez Arellano JL.),
	(Prieto Valtueña, J.M.),
	(Rozman & Cardellach, L.),
	(Smith & Farrell),
	(Stryer & Rubin),
	(Surós & Surós),
	(Swartz, MH),
	(Haines, D.),
	(Kandel, e.a.),
	(Bear, e.a.),
	(Blumenfeld, H.),
	(Diamond, e.a.),
	(Kiernan, & R.),
	(Martín, J.H.),
	(Ojeda, e.I.),
	(Puelles, L. e.),
	(Snell, R.),
	(Schünke, e. a.),
	(Brunton, e.a.),
	(Laurence Brunton. Bruce Chabner),
	(Florez, e.a.),
	(Bhat, e.a.),
	(Golan, e.a.),
	(Loose., R. Y.),
	(Lorenzo, e.a.),
	(Lüllmann, e.a.),
	(Neal, M.),
	(Page, B.),
	(Preston, C.),
	(Rang, e.a.),
	(Richards, e.a.),
	(Rodríguez, CR.),
	(Trevor, e.a.),
	(Katzung, Bertram,Trevor),
	(Whalen, e.a.),
	(Abbas, Abul K., Lichtman, Andrew H.H., Pillai, Shiv.),
	(Karen C. Carroll et al),
	(Kenneth J. Ryan),
	(John E. Bennett, Raphael Dolin, Martín J. Blaser),
	(Murray Patrick R., Rosenthal Ken S., P Faller Michael A.),
	(Roberto Arenas Guzmán),
	(Doan T., Melvold R., Viselli S., Waltenbaugh C.),
	(Male D., Brrostoff J.,Roth D., Roitt I.),
	(Méndez Lj, López R., Hernández F.),
	(Owen J., Punt J., Stranford Sa.),
	(Pavón Romero L., Jiménez Martinez Mc, Garcés Me),
	(Delves, Martín, Burton, Roitt),
	(Tay J., Gutierrez M., Molina J., López R., Manjarrez M.),
	(Streiner, David L.),
	(Alfredo de Jesús Celis de la Rosa),
	(Cobo, Erik),
	(Dawson, Gail F.),
	(Norman, G. S.),
	(Pagano, M.G.),
	(Taucher, E.),
	(Black & Andreasen),
	(Ricardo Capponi Martínez),
	(Carlat D.),
	(Casey &Kelly),
	(Gelder et al.),
	(Eguiluz Uruchurtu I y Segarra Echebarría R.),
	(Ganti & Kaufman),
	(Owen et al.),
	(Oyebode, Femi),
	(Semple & Smyth),
	(Shea, Shawn Christopher),
	(Valdivia, Mario),
	(Vallejo Ruiloba J.),
	(VVAA),
	(Pérez, A.J.),
	(Hammer & M.),
	(Laso, F.),
	(Silbernal, &.L.),
	(Reissner, R.),
	(Schneider, Arthur-Szanto, Philip),
	(Mandell, Douglas and Bennet),
	(Carey, e.a.),
	(Carroll, e.a.),
	(Engleberg, N.C.),
	(Murray, e.a.),
	(Abbas, e.a.),
	(Bauman, R.),
	(Goering, e.a.),
	(Cuello, G.),
	(Gordis, L.),
	(Ruiz, M.),
	(Ajetunmobi, O.),
	(De Irala, E.J.),
	(Fletcher, e.a.),
	(Greenhalgh),
	(Hulley, e.a.),
	(Merrill, R. M.),
	(Moore, &.M.),
	(Rothman, K.J.),
	(Straus, e.a.),
	(Szklo, &.N.),
	(Weiss, N.L.),
	(Brady, H.),
	(Cockerham, C. William),
	(Gabe, Bury, Mike, & Elston, Mary Ann),
	(Browner, C. H.),
	(Canguilhem, G.),
	(Castro, R. & Bronfman),
	(Conrad, P.),
	(Durkheim, E.),
	(Duarte, NE.),
	(Foucault, M.),
	(Gaete, J.),
	(Good, B.),
	(Kottow, M.),
	(Mechanic, D.),
	(Morsy, Soheir A.),
	(Schepper-Hughes, Nancy & Lock, Margaret),
	(McGee, G.),
	(Gracia, D),
	(Herranz Rodriguez, G.),
	(Meckler, A.),
	(Randels, P. &.),
	(Vaughn, L.),
	(Euliano & Gravenstein ),
	(Jiménez Murillo y Montero Pérez),
	(Giménez, M.),
	(Quíck et al),
	(Kumar & Clark),
	(Ian Wilkinson),
	(Mandell, J.),
	(Pagana et al),
	(Arancibia y Ugarte),
	(Caimi y Caimi),
	(Herrera et al),
	(Rivas Jiménez, M),
	(Brunicardi et al),
	(Burdiles, P.),
	(Carvajal, C.),
	(Doherty, G.M.),
	(Espinoza R.),
	(Parrilla Paricio y Landa García),
	(Townsend et al),
	(Nicola Zammit),
	(Benjamín, I.),
	(Bhat et al),
	(Douglas et al),
	(Goic et al),
	(Laso, F.J.),
	(McGee, S.),
	(Pérez Arellano, A.J.),
	(Prieto Valtueña, JM),
	(Raftery et al),
	(Surós y Surós),
	(Lindsay & Bone),
	(Hammer & McPhee),
	(Kasper et al),
	(Kemper, e.a.),
	(Kumar y Clark),
	(Adams, A.),
	(Alvarez, V. & Antuña, R.),
	(Aminoff et al),
	(Biller, J.),
	(Barinagarrementeria),
	(Fuller, G.),
	(Greenberg et al),
	(López-Escobar, FM.),
	(Mumenthaler et al),
	(Ropper et al),
	(Vergara, E. & Fonck, L.),
	(Weiner et al.),
	(Wilkinson & Lennox),
	(Yañez, A.),
	(Zarranz, JJ.),
	(Cowen et al),
	(Owen et al),
	(Shea CS.),
	(Beaglehole & Bonita),
	(Gestal-Otero & Fernández-Crehuet),
	(Alvarez-Dardett & Colomer),
	(Frías Osuna, A.),
	(Málaga & Restrepo),
	(Pinger & McKenzie),
	(Schneider, M.),
	(Turnock, B.),
	(Cunningham G., Redstone, C.),
	(Soars L.),
	(McCarter),
	(McCarthy, M., McCarten, J. & Sandiford, H.),
	(Andormo & Ivone),
	(Oneto & Fischer),
	(Toy et al),
	(Annas, G.),
	(Johnson et al),
	(Murphy, T.),
	(Pence, G.),
	(Randels & Pierce),
	(Martínez R., A., Erstnes B., G.),
	(Miller M.),
	(Marco, F.),
	(Skinner HB et al),
	(Sam W. Wiesel, John N. Delahay, Marc C. Connell),
	(American Academy of Orthopedic Surgeons (AAOS)),
	(Gasic Brzovic, Miguel),
	(Greene, WB),
	(Marco Martínez y Urda Martínez-Aedo),
	(Munuera Martínes, L.),
	(DeFroda. Steven F, Hansen. Heather, Gil. Joseph A, Hawari. Ashraf H, Cruz. Aristides I. Jr.),
	(Di Chen, Jie Shen, Weiwei Zhao, Tingyu Wang, Lin Han, John L Hamilton & Hee-Jeong Im),
	(Hvid Ivan, Parsch Klaus),
	(Albala, C, et al),
	(Astiasarán, I & Martínez, J.A.),
	(Barker, D.),
	(Gil Hernández, A.),
	(González de León, D. et al),
	(Salas-Salvado J. et al),
	(Mahan, L.K.& Escott-Stump, S),
	(Mataix, J.),
	(Requejo, A. & Ortega, O.),
	(Román, D.),
	(Salas, L.),
	(Alejandro, H.),
	(Cervera, P.e.),
	(EGO-Chile, M.d.),
	(FAO),
	(Marielle, C.e.),
	(Minsal, Mineduc, Vida Chile, Chile Deportes, Inta, Universidad de Chile),
	(Moreiras, O. (s.f.)),
	(OPS/OMS, M.),
	(Pizarro, F. et al),
	(Planas, M. y P.),
	(Vazquez, C.),
	(Argimón Pallás, J. & Jiménez Villa, J.),
	(Cuadras, C.),
	(Dillon, W. & Goldstein, M.),
	(Hernández, S. et al),
	(Milton, J. & Tsokos J.O.),
	(Milton, S.),
	(Miranda, C. et al),
	(Pita-Fernández, S. & Pértegas-Díaz, S.),
	(Kaisary et al),
	(Al-Sukani et al),
	(Cruz Hernández et al),
	(San Miguel y Sánchez Guijo),
	(Albert, Lori),
	(Rúa-Figueroa Fernández de Larrinoa, I),
	(Sánchez et al),
	(O'Young et al),
	(Frontera et al),
	(González-Mas, R.),
	(Maitin I.),
	(Miranda Mayordomo y Flores García),
	(Montgomery, H. &.),
	(Pleguezuelos Cobo et al),
	(Viladot Pericé et al),
	(Zollman F.),
	(Alonso, I Simón, P. Sanchez),
	(Guarda & Gubelin),
	(Wolff et al),
	(Bolognia et al),
	(Ferrándiz, C.),
	(Habif, T.),
	(Lubliner, D.),
	(VV.AA.),
	(Lambert, J. Lambert, S.),
	(Fong, e.a.),
	(Holzinger, A.),
	(Hoyt, R.),
	(Lahoz-Beltrá, R.),
	(Lyuboslavsky, V.),
	(Hulley et al),
	(Jiménez Villa et al),
	(Katz, M.H.),
	(Argimón-Pallás y Jiménez-Villa),
	(Browner, W.),
	(Byrne, D.),
	(Cobo, E. M.),
	(Dawson, G.),
	(De Irala, J.),
	(Duartge, O. &. Y.),
	(Foriste, B. &.),
	(Hall, G.),
	(Hernández-Sampieri et al),
	(Hodges & Tomas),
	(Jagaadesh et al),
	(Nieto & Szklo),
	(Ruiz Morales & Gómez Restrepo),
	(Straus et al),
	(Watkins & Portney),
	(Katz et al),
	(Gil Gregorio, P),
	(Martín Z., et al),
	(Restepro y Málaga),
	(Acastello Eduardo),
	(Ashcraft Keith),
	(Behrman R. y kliegman R.),
	(Cruz, M.),
	(Fuller, J.),
	(Muñoz Calvo M.T.),
	(Games EJ, et al),
	(Klass M.A., B.K.),
	(Marcdante, KJ, et al),
	(Martínez y Martínez, R.),
	(Bernstein D, Shelov SP.),
	(CENECET),
	(Sabiston D.),
	(Valoria J.),
	(Lissauer T, Clayden G.),
	(Ruiz Frutos et al),
	(LaDou, J. & Harrison, R.),
	(Alli, B.),
	(Ceballos Atienza, R.),
	(Fernández, R.),
	(Hodgson, Ernest),
	(Koh & Aw.),
	(Nava, R.),
	(Nogue-Xaraus S.),
	(Ojeda Gil, José A.),
	(Oliva, E.),
	(Pillay, VV),
	(Rojas, M.),
	(Graue E.),
	(García-Feijoo, Julián y Pablo-Júlvez, Luis E.),
	(Alezzandrini, A.),
	(Kanski J.),
	(Cremers AL, Bowers J., et al),
	(Palis, A.G.),
	(Chantal et al),
	(Martín, Z. et al),
	(Kopitowski et al),
	(Montero, L.),
	(Smith & Shimp),
	(D'Hyver & Gutierrez),
	(Gutiérrez et al),
	(Ham et al),
	(King & Lipsky),
	(Marín Larraín PP.),
	(Gisbert Clabuig, J.A.),
	(Teke Schlicht, A.),
	(Hernández, C.),
	(Madea B.),
	(Saukko P., Knight, B.),
	(J. Wyatt, T. Squires, G. Norfolk, J. Payne-James),
	(Humberto Giugni),
	(Vargas Alvarado, E.),
	(García Garduza, I.),
	(García Arellano, JF.),
	(Di Maio, V., Dana, S.),
	(Rodríguez Calvo MS, Vazquez-Portomeñe F.),
	(Rodríguez Calvo MS),
	(Bogusz, M.J.),
	(Dart, R. C.),
	(Levine, B.),
	(Butler, JM),
	(Jobling MA, Gill P),
	(Kayser M., de Knijff P.),
	(),
	(Cuello M., Miranda V. Y Ralph C.),
	(Cunningham, Gary, Leveno, Kenneth J., Bloom, Steven L., 6 Spong, Catherine Y.),
	(Bradshaw, Karen D., Corton, Marlene M., Halvorson, Lisa M., Hoffman, Barbara L., Schaffer, Marlene., & Schorge, John O.),
	(Ebensperger, E., & Lizana, J.),
	(Beckmann et al),
	(Creasy & Resnick),
	(Dechernety et al),
	(Gabbe et al),
	(Hoffman, B. et al),
	(Kenny & Bickerstaff),
	(lobo et al),
	(Matorras y Remohi),
	(Roura y Rodríguez),
	(Strauss & Barbieri),
	(Kane et al),
	(Rodríguez & Lazcano),
	(Thompson et al),
	(Arancibia & Ugarte),
	(Rozman y Cardellach López),
	(Lalwani, A.),
	(Peñaranda, A.),
	(Arrieta, P. & Prado, C.),
	(Chan & Goddard),
	(Montila, M. ),
	(Pensak, M.),
	(Poch, J.),
	(SEOR, S.E.-F.),
	(Tysome, K. &.),
	(Longmore et al),
	(Acuña, R. e.),
	(Schneider, & L.),
	(Black, &.A.),
	(Burton, N.),
	(Capponi, M.R.),
	(Carlat, D.),
	(Casey, &.B.),
	(Casey, &.K.),
	(Cowen, e.a.),
	(Eguiluz, U.I.),
	(Fish, F.),
	(Ganti, &.K.),
	(Gask, e.a.),
	(McCarron, e.a.),
	(Milhorn, H.),
	(Morris, &.R.),
	(Owen, e.a.),
	(Oyebode, F.),
	(Semple, &.S.),
	(Shea, C.),
	(Tizón, G.e.),
	(Valdivia, M.),
	(Vallejo, R.J.),
	(VV.AA. CIE-10),
	(Herrera, e.a.),
	(Espinoza, R.),
	(Parrilla, P.),
	(American Academy of Orthopedic Surgeons),
	(Skinner, H),
	(Balibrea, J.),
	(Dashe, K.),
	(Hoffman, &.S.),
	(Lobo et al),
	(Resnick., C. &.),
	(Chantal, e.a.),
	(Martín Zurro, Amando),
	(Alvarez, A.R.),
	(Burr, C.P.-L.),
	(Gilbert, e.a.),
	(Montero, J.T.),
	(Nerio., R.G.),
	(Oyarce, P.A.),
	(Soto G. Lutzow J,M.A.),
	(Arancibia, Y. U.),
	(Rodríguez, y. L.),
	(Thompson, e.a.),
	(Saieh, C.),
	(Guerrero, F.e.),
	(Herrera, &.Q.),
	(Hughes, &.K.),
	(Kliegman, e.a.),
	(Paris, M.e.),
	(Pérez, P.e.),
	(Rostion, C.),
	(Schonhautt, y.A.),
	(Shah, e.a.),
	(White, A.),
	(Zitelli, e.a.),
	(Fournier, M.C.),
	(Reyzábal, M. V., & Casanova, M. A.),
	(Vallés, A. A.),
	(Verderber, R. F.),
	(Britton, J. R., & Bello, l.),
	(Swokowski, E. W., & Trigueros, M.),
	(Miller, C. D., Heeren, V. E., & Hornsby, E. J.),
	(Jelen, B.),
	(Menchén, P. A.),
	(Hawley, D., & Hawley, R.),
	(Virginia Caccuri),
	(Frye, C., & Scott, P. P.),
	(Online Training Solutions, lnc.),
	(Luque, C. M. J.),
	(Koontz, H., & Weihrich, H.),
	(Chiavenato, l., Mascaró, S. P., & In Mares, C. J.),
	(Jones, G. R., George, J. M., & ProQuest),
	(Robbins, S. P., & Coulter, M.),
	(Lavigne, M. A., & In Mares, C. J.),
	(Chiavenato, l.),
	(Charles T. Horngren, Walter Harrison Jr. y M. Suzanne Oliver),
	(Julio Bosch Bousquet, Luis Vargas Valdivia),
	(Parkin, M., & Esquivel, G, & Avalos M.),
	(Mankiw, G.),
	(Beker, V., & Mochón, F.),
	(Massad, C., & Pattillo, G.),
	(Maximiano, A. C. A., & Chávez, S. J. L.),
	(Dracker, P. F.),
	(Kawasaki. G.),
	(Fernández, J.),
	(Hill, H.),
	(Marks, J.),
	(McCarthy, M., McCarten, J., & Sandiford, H.),
	(Murphy, R.),
	(Wilson, K., & Healy, T.),
	(Jones, G. R., George, J. M., & ProQuest.),
	(Chiavenato, l., Sapiro, A., & Mascaró, S. P.),
	(Chiavenato, l., Guzmán, B. M. P., & Mascaró, S. P.),
	(Brigharn, E., & Houston, J.),
	(Besley, S., & Brigham, E.),
	(Van Horne, J.),
	(Torres Gabriel),
	(Carlos A. González M,),
	(Humberto Varas C),
	(Boggino, N.),
	(Novak, J. D., & González, C.),
	(Sambrano, J., & Steiner, A.),
	(Colmenar, S. A.),
	(Wilson, K.),
	(Femández, S. E.),
	(Koontz, H., Weihrich, H., Sánchez, S. G. A., & Gómez, M. J.),
	(Yarela, R.),
	(Cohen, K. D., & Asín, L. E.),
	(Kelley, T., & Littman, J.),
	(Schilling, M. A.),
	(les, M. A.),
	(Arias, G. F., & Heredia, E. V.),
	(Byars, L. L., & Rue, L. W.),
	(Chiavenato l.),
	(Dressler G.),
	(Sapag, N.),
	(Ocarnpo, S. J. E.),
	(Baca, G.),
	(Kotler, P., Armstrong, G., & Cámara, l. D.),
	(Dessler, G., Varela, J. R., Pineda, A. L. E., & Campos, O. V.),
	(Varela, R.),
	(Costa, M., & López, M. E.),
	(Sapag, C. N.),
	(Muñoz, R. C.),
	(Ñaupas, P. H., Yaldivia, D.M. R., Palacios, Y. J. J., & Romero, D. H. E.),
	(Hernández, S. R., & Fernández, C. C. B. L. M. P.),
	(Barbera, E.),
	(Klenowski, V.),
	(Valles, M. M. S.),
	(Adler, R. 8., Elrnhorst, J. M., Mascaró, S. P., & González, P. J. R.),
	(Reyzábal, M. V., & Casanova, M.),
	(Vallés, . A.),
	(Britton, J. R., & Bello, I.),
	(• Swokowski, E. W., & Trigueros, M.),
	(jelen, B.),
	(Online Training Solutions, Inc.),
	(Jiménez, J., & Velilla, N.),
	(Kerr, P. F.),
	(Cornelis Klein),
	(Heinrich, E. W.),
	(García, M.C.),
	(Tarbuck, E. J., & Lutgens, F. K.),
	(Edwards, T.),
	(Barettino, D., Wimbledon, W. A1 P., & Gallego, E.),
	(Mourgues. F. A., Schilling, M., & Castro, C.),
	(Gonzalez, M. R.),
	(Fernandez, B. P.),
	(Dorado, A. C.),
	(Dana, J. D., & Hurlbut, C.),
	(Groeber, P.),
	(Klein, C., & l lurlbut, C. S.),
	(UDA English Center),
	(Bannister. A., Raymond, S., Baker, R., de la Cera Alonso, J., & López, R. O.),
	(Domínguez García Tejero, F., Thompson, M. M., Lillcsand, T. M., Kiefer, R. W., Venegas, M., Veruette, F., & Schmoock Pivaral, W. J.),
	(Gutiérrez, C. P., & Nieto, A. L. M.),
	(Domínguez García-Tejero, F.),
	(McCormac, J.),
	(Romeo, C. T.'!'. R.),
	(Casanova, L.),
	(Leonardo, C. M.),
	(MARIA ISABEL SI LLANO,JORGE PEREZ ROJAS),
	(Buzai, G. D., & Baxendale, C. A.),
	(Gómez Delgado, M., Cano, B., & Ignaciocoaut, J.),
	(Sendra, J. B.),
	(Romero, T. D .. & Martínez, E. P.),
	(González Bonorino, F.),
	(Perkins, D., l Ienke, K. R., & Kevin, R. 11.),
	(Kraus, 11., l lunt, E. F .. Ramsdell, W. S., & Alvargonzález, L. N.),
	(Cochran, W. G.),
	(Ballou, R. H., & de Lemus, P. R.),
	(Silvia Maturana),
	(Bustillo Revuelta M. y López J imeno C.),
	(Novitzky A.),
	(Millan A.),
	(Castro Dorado, A.),
	(Rojas Caballero, D. and Paredes, J.),
	(Sillitoe Richard.),
	(Tarbuck, E. and Lutgens, F.),
	(Tosdal R. and Richards J.),
	(Andrés Mac-Lean),
	(Comisión Chilena del Cobre),
	(Castro, A),
	(Lisie, R.),
	(Hans Niemeycr R.),
	(Ayala-Carcedo, r:.J. y Oleína Cantos, J.),
	(Keller, E.A.),
	(CEPAL-GTZ),
	(Instituto Tecnológico y Geominero de España),
	(Anguita Virella, r:. y Moreno Serrano, F.),
	(Ayala, F. y [ordá, J.F.),
	(Aswathanarayana, U.),
	(Tugendhat, E., Vicuña,A.. M., & López, C.),
	(Muríoz, R. C.),
	(Naupas, P. H., Valdivia, D. M. R., Palacios, V. J. J., & Romero, D. H. E.),
	(Fernández. S. R., & Fernández, C. C. B.L.M. P.),
	(Lewin R., López A. . Martínez S., Rojas D., Zanocco P.),
	(Chamorro M.),
	(Reyes,C., Dissett, L.,Gormaz, R.,Geometría.),
	(Stanley Clemens, Phares O, Daffer y Thomas Vooney.),
	(Moise E., Downs F.),
	(Gutierrez, F),
	(Papalia, Diane),
	(Ruz, J.),
	(Sharp, Margaret),
	(Travers, Robert),
	(Suarez, M),
	(Gonzàlez-Anleo,Juan),
	(Biertedt, Robert),
	(De Azevedo,Fernando),
	(Durkheim, Emile),
	(Banks, Olive),
	(Bonal, Xavier),
	(Bourdieu, P.),
	(Bourdieu ,P y Passeron, J.C.),
	(Bunge, Mario),
	(Chinoy , E.),
	(Corcuff, Philippe),
	(Garretón, Manuel Antonio),
	(González-Anleo, Juan),
	(Moreno B. Ernesto),
	(Tirado Benedi, Domingo),
	(Wright Mills, Charles),
	(Briones, G.),
	(Hessen, J.),
	(Peters , R.S.),
	(Morin, Edgar),
	(Althusser,Louis),
	(Apple,M.),
	(-Brugger, W.),
	(Cerutti G.,Horacio),
	(Cirigliano, G.),
	(Durkheim , E.),
	(Ferrater Mora, J.),
	(Freire, Paulo),
	(Giannini, H.),
	(González R.,A.),
	(Fromm, E.),
	(Hegel, G.),
	(Jasper, K.),
	(Maritain, Jacques),
	(Munizaga A.,R),
	(Pérez,H.C.),
	(Peters, R.S.),
	(Politzer,G.),
	(Savater, F.),
	(Weber, M.),
	(Arredondo,Marcial),
	(Comella, A),
	(Comamalas, J.),
	(Gombrich, E, Rafael Santos Torroella, Javier Seto),
	(Wolf, Rachel),
	(Parramon),
	(Ander-Egg Ezequiel. Aguilar Idáñez María José),
	(Barmat de Miles, Alicia B., Ramos, Laura.),
	(Zuccherini Renzo),
	(de Mena González, Ana),
	(Reyes,C., Dissett, L.,Gormaz, R.,Geometría. Colección ReFIP),
	(Stanley Clemens, Phares O. Daffer y Thomas Vooney),
	(Reyes,C., Dissett, L.,Gormaz, R.),
	(Stanley Clemens, Phares O'Daffer y Thomas Vooney),
	(Cofré,A.,&Tapia, L.),
	(Azcárate, et al),
	(Rico, L., Segovia, I.),
	(Lerner, D. et al),
	(Martínez, P., Rico, L.),
	(Riveros, M; Zanocco, P.),
	(Gallego, R.),
	(Tobon, S.),
	(Antunes, C.),
	(García, Ana & otros),
	(Gessel, Arnold.),
	(Gutiérrez, F),
	(Toledo, Virginia),
	(Suarez, M,),
	(Aharoni, Ron.),
	(Castro, Enrique),
	(Cofré, J. A., Tapia, A. L., &Lucchini, G.),
	(Yáñez .J et al),
	(Cofré ,J .A.),
	(Fernández Bravo, José Antonio),
	(Gómez Chacón, Inés María),
	(Riveros Rojas, Marta coaut.),
	(Arteaga Martínez, Blanca.),
	(Broitman, Claudia comp.),
	(Broitman, Claudia.),
	(Segovia Alex, Isidoro coord.),
	(Chamorro, M.),
	(Stacey, Kaye.),
	(De La Vega, Alejandro.),
	(Rodríguez M., Eugenia, Kaliski K., Enrique.),
	(Puccio, Alicia.),
	(Alvares A),
	(Arauyo Joâo B y otro),
	(Aususbel D.),
	(Bruner J.),
	(Carretero, M.),
	(Carretero, M. Bennet, N., Järvinen A., Pope, M., Ropo, E.),
	(Coll Cesar,),
	(Coll, Marchesi y Palacios),
	(Daud B.; Grahome F),
	(Good, T, L. y Brophy J),
	(Gardner H.),
	(Hagarty S.; Pocklington K),
	(Henson, K.),
	(Klinger C.),
	(Losada, J.L.),
	(Loughlin C.E. y otro),
	(Mayer, R.),
	(Pilar y cols.),
	(Pérez M. Royman, Gallego B. Rómulo),
	(Poeydomenge. M.),
	(Pozo, J.I,),
	(Förster, C.E.),
	(San Martí N.),
	(REAL ACADEMIA ESPAÑOLA),
	(FUENTES, JUAN LUIS),
	(CONDEMARÍN, MABEL Y MEDINA, ALEJANDRA),
	(CONDEMARÍN, MABEL y MEDINA, ALEJANDRA),
	(Araneda, A., E. Chandía y M. Sorto),
	(Martínez, S.,Varas, M.),
	(Ronald E. Walpole, R.,H,&Vásquez, t.G.),
	(Lewin, R., López, A., Martínez, S., Rojas, D. y Zanocco, P.),
	(Albert, L., & Simon, P.),
	(López, A., Parada, A., & Simonetti, F.),
	(Novara, D., & Passerini, E.),
	(Goleman, D.),
	(Locke, EA),
	(Segal, J.),
	(Rulicki, S., & Cherny, M.),
	(Steiner, V. y Perry, R.),
	(Stevens, J. O.),
	(Bloom, Benjamín S.),
	(Da Costa Leiva, Miguel.),
	(Gairín Sallán, Joaquín),
	(García Requena, Filomena),
	(Iglesias Díaz, Juan),
	(Juidias Barroso, Jerónimo),
	(De La Vega, Alejandro),
	(Rodríguez M., Eugenia, Kaliski K., Enrique),
	(Puccio, Alicia),
	(Gutierrez, F.),
	(Suarez, M.),
	(Contreras, L.,Carrillo,J.),
	(Cultural S.A.),
	(Billings, W.),
	(Weisz, P.),
	(VILLE, C. A.),
	(Vila, L.),
	(Hernández-Sampieri, R., Mendoza, C.),
	(CURTIS, H. Y BARNES, N. S.),
	(KIMBAL. J. W.),
	(SOLOMON, E. P., BERG, L. R. y VILLE, C.),
	(Squeo,F., Osorio, R., Arancio, G.),
	(Cebrián de la Serna, Manuel.),
	(Marín Díaz, Verónica),
	(Hurtado Canales, Guillermo),
	(Labinowicz, E.),
	(Rondal, J.),
	(Condemarín, M.),
	(Condemarín, M. y Allende F.),
	(Condemarín, M. Chadwick W y Milicic N.),
	(Jimenez, J. y Ortizm, M.),
	(Solís, M.),
	(López jiménez , S.),
	(Ferreiro, E.),
	(Adam, E. et al.),
	(Bisquerra, R., Pérez-González, J. C., & García Navarro, E.),
	(Bisquerra, R.),
	(Milicic, N.),
	(CPEIP, M.),
	(Ferreiro, E y Gómez, M.),
	(Vivaldi, M.),
	(Rodríguez, G.),
	(Cuervo, R.J.),
	(Fuentes, J. L.),
	(Ortega y Gasset, José),
	(De Unamuno, Miguel),
	(Sánchez, J),
	(Cortazar, Julio),
	(Neruda, Pablo),
	(Rulfo Juan),
	(Huidobro Vicente),
	(Marx Wartofsrky),
	(Armando Asti Vera),
	(Roberto Hernández Sampieri, Carlos Fernández Collado, Pilar Baptista Lucio Hernández Sampieri, Roberto, Baptista Lucio, Pilar, Fernández Collado, Carlos),
	(Miguel S.),
	(Edgar Morin),
	(Bunge, M.),
	(Rodríguez, G.; Gil, J. y García, E.),
	(Carlos Pérez Soto),
	(León, O. E Montero, I.),
	(Massara Kurtz, Celia),
	(Pruzzo de Di Pego, Vilma.),
	(Cebrián de la Serna, Manuel),
	(Da Costa Leiva, Miguel),
	(Cassany, D.),
	(Marchant T, R. I.),
	(Meneses, E. H.),
	(Bermeosolo, J.),
	(Raymond Chang),
	(Delgado, J.),
	(Elliot, J.),
	(Fernández, A. M. y López, M.),
	(Goetz, J. P. Lecompte, M.),
	(Guilford, J.P. & Fruchter, B.),
	(Hernández Sampieri, R. y otros),
	(Kemmis S., Mctaggart R.),
	(Pérez Serrano, Gloria),
	(Pérez, C.),
	(Ilabaca, J. S.),
	(Borrego, C.),
	(Bartolomé, A.),
	(Camilloni, A),
	(Araya, F),
	(Aranda, A),
	(Domínguez, M),
	(García, E),
	(Aurell, Jaume),
	(Prats, Joaquín),
	(Gairin Sallan, Joaquin),
	(Garcia Requena, Filomena),
	(Juidias Barroso, Jeronom),
	(Contreras, J.),
	(Bohm, W., & Schiefelbein, E.),
	(Echeita, G.),
	(Hargreaves, A.),
	(Oliva, M.),
	(Peralta Espinosa, M.),
	(Sacristán, J.),
	(Sacristan, J.),
	(Stainback, S., & Stainback, W.),
	(Massara Kurtz, Celia.),
	(Anton, Howard),
	(Baldor, J.),
	(Cameron, Edward.),
	(Calter, Paul.),
	(Elal, Salim: Cuadra, Eduardo: Mercado, Roberto),
	( Hawk, Minor.),
	(Lehmann, Charles.),
	(Porschle, Francisco.),
	(Swokowski, Earl.),
	(Sobel, Max.),
	(Warner, Frank: Mc Neary, Matthew.),
	(Arancibia, Sara: Mena, Jaime.),
	(Ayres, Frank: Mendelson, Elliot.),
	(Burgos, Juan.),
	(Freyhoffer I.),
	(Larson, Ron: Hostetler, Robert: Edwards, Bruce.),
	(Simmons, George: Krantz, Steven.),
	(Barraza, Carlos),
	(Díaz, Luis: Ortega, Victor: Gillmore, Michael),
	(Gonzáles, Manuel: Castejón, Rafael: Gómez, José: Martínez, Juan: Méndez, Ester: Mechón, Amelia.),
	(Paschoal, José.),
	(Samuelson, Paul.),
	(Trívez, Francisco.),
	(Bosch, Julio: Vargas, Luis.),
	(Cashin, James.),
	(Guajardo, Gerardo.),
	(Horngren, Charles.),
	(0),
	(Romero, Álvaro.),
	(Torres, Gabriel.),
	(Bateman, Thomas: Snell, Scott.),
	(Chiavanato, Idalberto.),
	(Hitt, Michael.),
	(Koontz, Harold.),
	(Robbins, Stephen.),
	(Arratia Isabel.),
	(Hill, Richard.),
	(Lang, Sege.),
	(Spiegel, Murray.),
	(Vera, Julio.),
	(Zill, Dennis.),
	(Apostol, Tom.),
	(Barahona, Manuel.),
	(Larson, Ron.),
	(Browing, Edgar.),
	(Grave, Ana Luisa.),
	(Gravelle, Hugh.),
	(Mankiw, N. Gregory.),
	(Mochón, Francisco.),
	(Parkin, Michael.),
	(Álvarez, Alzaga: Vega, M.),
	(Horngren, Charles: Harrison, Walter: Oliver, M. Suzanne.),
	(Perdomo, Abraham.),
	(Cooper, Dominic: Robertson, Iván: Tinline, Gordon.),
	(Fayol, Henri.),
	(Reyes, Agustín.),
	(Robbins, Stephen: DeCenzo, David.),
	(Varela, Ricardo.),
	(Cairo, Osvaldo: Guardati, Silvia.),
	(Hernández, Roberto.),
	(JOYANES A., Luis),
	(Balmes, Zoila: González, Gracia),
	(Cessany, Daniel.),
	(Ender-Egg, Ezequiel: Aguilar, María.),
	(Gonzáles, Antonio.),
	(Pérez, Héctor.),
	(Briones, Guillermo.),
	(Chao, Lincoln.),
	(Cortés, Milton.),
	(Fernández, Pedro.),
	(Miller, Irwin: Freud, John: Johnson, Richard.),
	(De Juan, Rebeca: Mochón, Francisco.),
	(Dornbusch, Rudiger: Fischer, Stanley: Startz, Richard.),
	(Larraín, Felipe: Sachs, Jeffrey.),
	(Mochón, Asunción: De Juan Rebeca.),
	(Arredondo, María.),
	(Cuervo, Joaquín: Osorio, Jair.),
	(Horngren, Charles: Dator, Srikant: Rajon, Madhev.),
	(Polimeni, Ralph.),
	(Vargas, Luis.),
	(Eyssautier, Maurice.),
	(Rodríguez, Gregorio.),
	(Ruiz, José.),
	(McLeod, Raymond.),
	(Piattini, Mario.),
	(O´Brien, James: Marakas, George.),
	(Daniel, Karen: Asín, Enrique.),
	(Di Biase, Aldo.),
	(Elal, David.),
	(Taha, Hemdy.),
	(Haeussler, Ernest: Richar, Paul: Wood, Richard.),
	(Hillier, Mark.),
	(Casas, Miguel.),
	(Díaz, Alfredo.),
	(Levine, David: Timothy, Krehbiel: Berenson, Mark.),
	(Levin, Richard: Rubin, David.),
	(Lohr, Sharon.),
	(Peña, Daniel.),
	(De Juan, Rebeca: Mochón, Asunción.),
	(Grave, Ana Luisa. Parkin, Michael.),
	(Salvatore, Dominick.),
	(Coudurier, Lucie.),
	(Instituto para la diversificación y Ahorro de la Energía),
	(Sierra, José: Penalver, Luis.),
	(· Lardent, Alberto.),
	(Ministerio de Justicia),
	(Gujarati, Damodar: Porter, Dawn.),
	(Pearson, Eduardo),
	(Wooldridge, Jeffrey),
	(Carbaugh, Robert),
	(Contreras, Hugo: Gonzáles, Leonel.),
	(Dornbusch, Rudiger: Fischer, Stanley.),
	(Garcías, José: Durán, Gemma.),
	(Hall, Robert: Lieberman, Marc.),
	(Ossa, Fernando.),
	(Taylor, George.),
	(Riggs, James.),
	(Sepúlveda, José: Sonder, William: Gottfried, Byron.),
	(Anthony J. Tarquin y Leland T. Blank),
	(Sapag, Nassir: Sapag, Reinaldo.),
	(Sapag, Nassir),
	(REYZÁBAL, Mª Victoria),
	(CASSANY, Daniel),
	(GARCÍA DEL TORO, Antonio.),
	(Gómez Torrego, Leonardo,),
	(Martínez De Sousa, José,),
	(BARRIENTOS  GRANDÓN, Javier),
	(Bravo Lira, Bernardino),
	(TOMÁS Y VALIENTE, Francisco),
	(Bravo  Lira,  Bernardino),
	(Salazar,  Gabriel,  Pinto  Julio.),
	(SAMPER POLO, Francisco),
	(DE ÁVILA MARTEL, Alamiro),
	( GUZMAN BRITO, Alejandro),
	(MIQUEL),
	(SCHULZ),
	(BERNARDO CARRASCO, José),
	(FERNÁNDEZ RODRÍGUEZ, Concepción),
	(LÓPEZ REYES, Alex),
	(BOBBIO, Norberto),
	(DWORKIN, Ronald),
	(SQUELLA, Agustín),
	(BLÁZQUEZ FERNÁNDEZ, Niceto),
	(COSTA, Joan.),
	(GABILONDO PUJOL, A.),
	(BÉJAR HURTADO, M.),
	(BONILLA, S),
	(BRAVO LIRA, Bernardino),
	(Salazar, Gabriel, Pinto Julio),
	(Gabriel, Pinto Julio),
	(ATIENZA, Manuel),
	(COHEN, Morris y NAGEL Emest),
	(Soto, Carlos),
	(CORREIA, Manuel),
	(SAUSSURE, Ferdinand de,),
	(VERDUGO, Mario y GARCÍA, María),
	(QUINZIO, Jorge y BERNALES, Gerardo),
	(NOGUEIRA, Humberto y CUMPLIDO, Francisco),
	(DUVERGER, Maurice),
	(LÓPEZ, Mario),
	(ALESSANDRI, A, SOMARRIV  A, M, y VODANOVIC, A.),
	(CLARO, Luis),
	(DUCCI, Carlos),
	(BARCIA, Rodrigo),
	(FIGUEROA, Gonzalo),
	(SEPÚLVEDA, César),
	(MOCHÓN, Francisco y  BEKER, Alberto),
	(BEKER y MOCHÓN),
	(Wonnacott y Wonnacott),
	(Larroulet y Mochón),
	(AGUIRREZABAL GRÜNSTEIN,  Maite),
	(ISLER SOTO, Erika),
	(SANDOV AL LÓPEZ, Ricardo),
	(Blackwell, Miniard y Engel),
	(Schiffman, Leon),
	(GAMBOA SERAZZI, Fernando.),
	(INFANTE CAFFI, María Teresa [ et al.]),
	( BENADA V A CATT AN, Santiago),
	(Cecilia Medina Quiroga y otros),
	(Roberto  Diaz Ruiz),
	(COLOMBO CAMPBELL, Juan),
	(PÉREZ RAGONE, Álvaro - NÚÑEZ OJEDA, Raúl),
	(GUILHERME MARINONI, Luiz [et al.]),
	(De la Oliva SANTOS, Andrés),
	(LANA TA FUENZALIDA, Gabriela),
	(Boisvert, J.),
	(Fermandois, Arturo),
	(González, Rodrigo),
	(Ruiz Tagle, Carlos),
	(Jaedelung, John),
	(Valdés, Domingo),
	(NOGUEIRA ALCALÁ, HUMBERTO),
	(CEA EGAÑA, JOSÉ LUIS),
	(NOGUEIRA, HUMBERTO Y CUMPLIDO, FRANCISCO),
	(GARROTE, EMILIO),
	(JIMÉNEZ LARRAÍN, Fernando y JIMÉNEZ MOOSLI, Fernando),
	(ALESSANDRI, SOMARRIV A, VODANOVIC.),
	(BARCIA L., RODRIGO),
	(DUCCI CLARO, CARLOS),
	(ALESSANDRI B., ARTURO),
	(DUCCI C., CARLOS),
	(FIGUEROA Y., GONZALO),
	(GARRIDO MONTT, Mario.),
	(CURY URZUA, Enrique),
	(POLITOFF, S. MATUS, P. RAMIREZ, M.),
	(SILVA SÁNCHEZ, Jesús-María),
	(DURAN,  Mario),
	(Sandoval López Ricardo),
	(Mayorga, Morales y Polanco),
	(Pozo Silva, Nelson),
	(STOEHREL MAES, Carlos),
	(ROMERO SEGUEL, Alejandro),
	(PÉREZ RAGONE, Álvaro NÚÑEZ OJEDA, Raúl),
	(CASARINO  VITERBO, Mario),
	(ORELLANA TORRES, Fernando),
	(GARCÍA, ROLANDO),
	(MORIN, EDGAR),
	(SOTOLONGO, PEDRO, DELGADO, CARLOS, BOLAÑA, MARlSA),
	(GÓMEZ, Taeli),
	(DANIEL PEÑAILILLO ARÉVALO),
	(GONZÁLO RUZ LÁRTIGA),
	(HERNÁN TRONCOSO LARRONDE),
	(MINISTERIO DE JUSTICIA),
	(ALESSANDRJ, SOMARRIVA Y VODANOVIC),
	(MEDINA QUIROGA, CECILIA Y NASH ROJAS, CLAUDIO),
	(NASH ROJAS, CLAUDIO),
	(ESPEJO Y., NICOLAS Y LEIVA G., CARLA),
	(HUBNER GALLO, JORGE),
	(MEDINA QUIROGA, CECILIA y MERA FIGUEROA, JORGE),
	(BERMÚDEZ SOTO, Jorge),
	(SOTO KLOSS, Eduardo),
	( PANTOJA BAUZA, Rolando),
	(CORDERO VEGA, Luis Alberto),
	( CELIZ DANZINGER, Gabriel),
	(GARCÍA, Rolando),
	(GRÜN, Ernesto),
	(MORIN, Edgar),
	(GÓMEZ,  Taeli),
	(SOTOLONGO, Luis; DELGADO, Carlos),
	(THAYER, William. NOVOA, Patricio),
	(GAMONAL CONTRERAS, Sergio),
	(UGARTE CATALDO, José),
	(PÉREZ RAGONE, Álvaro y Núñez Ojeda, Raúl),
	(RODRÍGUEZ PAPIC, Ignacio),
	(BORDALÍ, Andrés, CORTEZ, Gonzalo, PALOMO, Diego),
	(ROMERO SEGÜEL, Alejandro),
	(ASARINO VITERBO, Mario),
	(ABELIUK MANASEVICH, René),
	(COURT, Eduardo y WEGNER, Veronika),
	(RUZ LÁRTIGA, Gonzalo),
	(MEZA BARROS, Ramón),
	(ALESSANDRI, SOMARRIV A Y VODANOVIC),
	(POLITOFF, S. MATUS, P. RAMIREZ,M.),
	(SILVA  SÁNCHEZ, Jesús-María),
	(SCHÜNEMANN, Bemd),
	(LOPEZ SANTA MARIA, JORGE),
	(BARCIA LEHMANN, Rodrigo),
	(ALESSANDRI RODRIGUEZ, Arturo),
	(BOLOÑA KELLY, Germán),
	(CORDERO QUINZACARA, Eduardo),
	(GARRIDO MONTT, Mario),
	(ETCHEVERRY, Alfredo),
	(RODRÍGUEZ, Luis y OSSANDÓN, María),
	(DÍAZ GONZÁLEZ, Gonzalo),
	(ETCHEVERRY, A.),
	(BULLEMORE, Vivían y MACKINNON, John),
	(VARGAS PINTO, Tatiana),
	(SILVA,Rodrigo y VEGA, Francisco),
	(Justicia Constitucional y Derechos Fundamentales),
	(Eduardo Aldunate),
	(Emilio Pfeffer),
	(Director Luis Cordero),
	(Humberto Nogueira),
	(ORELLANA, Fernando),
	(ESPINOZA, Raúl),
	(CASARINO Viterbo, Mario),
	(ROMERO, Alejandro),
	(STOEHREL, Carlos),
	(THA YER, William. NOVO A, Patricio),
	(LANATA FUENZALIDA, Gabriela),
	(TOLEDO CORSI),
	(SILVA RUZ, Gabriel),
	(Legal Publishing Editores),
	(BARROS, Diego y PARGA, José),
	(FELIU SEGOVIA, Juan),
	(CONTRERAS STRAUCH, Osvaldo),
	(SANDOVAL LÓPEZ, Ricardo),
	(PUELMA ACCORSI, Álvaro),
	(PUGA  VIAL, Juan),
	(AMUNATEGUI, Andrés),
	(RIVERA BRAVO, Daniela),
	(VERGARA BLANCO, Alejandro),
	(Alejandro Vergara Blanco Abeledo Perrot),
	(FIGUEROA DEL RÍO, Luis),
	(LIRA OVALLE, Samuel),
	(ANSALDI DOMÍNGUEZ, Carmen),
	(OSSA BULNES, Juan),
	( BARRIENTOS, Javier y NOVALES, Aránzazu),
	(RAMOS PAZOS, René),
	(TRONCOSO LARRONDE, Hernán),
	(GOMEZ DE LA TORRE VARGAS, Maricruz),
	(FERNANDEZ BITTERLICH, Pedro),
	(BORQUEZ YUNGE, José),
	(AMUNÁTEGUI PERELLÓ, Carlos),
	(SEPÚLVEDA SOLAR, Doris),
	(HORWITZ, María y LOPÉZ, Julián),
	(MATURANA, Cristián y MONTERO, Raúl),
	(CHAHUÁN, Sabas),
	(DECAP FERNÁNDEZ, Mauricio),
	(SARRABAYROUSE, Eugenio),
	(MASSONE PARODI, Pedro),
	(ALVARADO URÍZAR, Agustina),
	(UGALDE, Rodrigo),
	(MEZA ENCINA Bárbara),
	(DE LA MAZA GAZMURI, Iñigo),
	(BARRIENTOS, Javier y NOVALES, Aránzazu),
	(PEDRALES GARCÍA DE CORTÁZAR, Antonio),
	(SQUELLA NARDUCCI, Agustín),
	(PECES-BARBA, Gregorio),
	(FOUCAULT, Michel),
	(AMUNATEGUI ECHEVERRIA, Andrés),
	(GÓMEZ, Rafael y EYZAGUIRRE,  Gonzalo),
	(SANDOV AL  LÓPEZ, Ricardo),
	(SILVA  RUZ, Gabriel),
	(HORWITZ, M.),
	(MATURANA, C.),
	(CASARINO, M.),
	(CHAHUÁN,  S.),
	(BARROS BOURIE, Enrique),
	(RODRIGUEZ GREZ,Pablo),
	(TAPIA RODRÍGUEZ, Mauricio),
	(COURT MURASSO, Eduardo),
	(APARISIS MIRALLES, Ángela),
	(ALCAÍNO, Rodrigo y CORTÉS DE LA CERDA, Matías),
	(LORENZO, Leticia),
	(HIGA SILVA, César),
	(BAILEY, Lee),
	(BERGMAN, Paúl),
	(FISHER, Roger),
	(NÚÑEZ OJEDA, Raúl),
	(URY, William),
	(ECO, Humberto),
	(ÁLVAREZ UNDURRAGA, Gabriel),
	(CORRAL T ALCIANI, Hernán),
	(AZÚA REYES, Sergio),
	(HERRERA, Enrique),
	(GARRIDO CHACANA, Carlos),
	(ALLIAUD, Alejandra),
	(BLANCO SUÁREZ Rafael),
	(MORENO HOLMAN, Leonardo),
	(VIAL CAMPOS, Pelayo),
	(Eco, Humberto.),
	(Álvarez Undurraga, Gabriel),
	(Corral Talciani, Hernán),
	(Carrillo, A.),
	(Mendez-Ximenez, A.),
	(Montero, A),
	(Gonzalez, A),
	(Kraft, W),
	(Torres, C),
	(Tomas, J.R.; Nelson, J.K.),
	(Hernández Sampiere, R),
	(Bizquerra, R),
	(Mahecha, S),
	(Sánchez Bañuelos, F),
	(Castillo, J),
	(Lomelín, M),
	(Maureira, F),
	(Hernández. A),
	(González, V.),
	(Rodriguez, J.),
	(Román, M.),
	(Freire, P.),
	(Devis, J.; Peiró, C.),
	(Fritzen, J.),
	(Gamboa S.),
	(Garcia A.),
	(Incarbone, O.),
	(Jiménez G.),
	(Lepe, A.),
	(Loscher, A.),
	(Martinez, J.),
	(Méndez, A),
	(Omeñaca, J & Ruiz, J),
	(Villa, J),
	(Watkins, D),
	(Bernal, D & Carrasco, H),
	(Rodríguez, M),
	(Ruiz, J),
	(AGUADO, X),
	(BERMESOLO, J),
	(BLASQUEZ, D),
	(FAMOSE, J),
	(CONTRERAS, O),
	(HERNÁNDEZ, J),
	(LAGARDERA, F.),
	(PIÉRON, M.),
	(SIEDENTOP, D.),
	(TARGET, CH. y CATHELINEAU, J.),
	(VÁSQUEZ, A.),
	(ARAYA, J. ET AL),
	(MÁRQUEZ, B. ET AL),
	(Bonnefoy, G.),
	(Cabero, A.),
	(Cavalli, D.),
	(Federación Internacional de Voleibol),
	(Hessing, W),
	(Iglesias, C.),
	(Jesus, D.),
	(Jáuregui, H.),
	(Kenny, B.),
	(Lucas, J.),
	(Moreno, P.),
	(Marsenach, J.),
	(Moreno, M.),
	(Pavlovich, M.),
	(Barrow H. Y Brown J.),
	(Benjumea, M.),
	(Blázquez, D.),
	(Del moral A.),
	(Le Boulch J.),
	(Perez, E.),
	(Ruiz L.),
	(Toro, S.),
	(Trigo, E.),
	(Zagalaz, M),
	(Mineduc),
	(Mercado, H.),
	(Rigal R.),
	(Saavedra, C.),
	(Tefarikis, E),
	(Collado, S., Otros),
	(Cratty, B.),
	(Lagardera, F.),
	(Le’ Boulch, J.),
	(Massion, J.),
	(Parlebas, P.),
	(Pikler, E.),
	(Rigal, R.),
	(Da Fonseca, V.),
	(Vaca, E., Otros),
	(Carrasco, D.),
	(Del Moral, A.),
	(Lagardera, F. & Lavega, P.),
	(Le Boulch, J.),
	(Ministerio de Educación),
	(Cratty, B. J. ),
	(Fernández-Marcote, A. E.),
	(Fonseca, V. ),
	(Pastor, P. J. L. ),
	(Lanuza, F & Torres, A ),
	(Navarro, F.),
	(Arenillas, R),
	(Soler, A.),
	(Jiménez, J.),
	(Conde, E.),
	(Vásquez, J.),
	(Brancacho, J.),
	(Conde, E),
	(Arenillas, R.),
	(Reyzábal, M.V., & Casanova, M. A.),
	(Hawley, D., & Hawley, R),
	(Lagunas, M. A.),
	(Enríquez, H. G.),
	(Guerrero Fernández, A., & Porras, C. A.),
	(Evans, E. E., & Yáñez, R. E.),
	(Carta, G. J. A.),
	(Ibáñez, P.M., Rosell, P. J. R., & Rosell, U. J. l.),
	(Vega K. J. C., & Rarñírez, M. S.),
	(Barberá, M. L.),
	(Hill, H.2016),
	(Méndez, M. J., & Rodríguez, R. L. M.),
	(Escudero, L. J. M., & Bornay, J. D.),
	(Ibáñez, P. M., Rosell, P. J. R., & Rosell, U. J. l.),
	(Vega, . K. J. C., & Ramírez, M. S.),
	(Mancera, F. M., & In Riaño, C. O.),
	(Asfahl, C. R., & Sanchez, G. G.),
	(Roldán, V. J.),
	(Martínez M, ML.),
	(Marriner Tomey A. MRA.),
	(Donahue MP.),
	(Kozier B.EG. B. A.S.S.),
	(Vial del Rio V.),
	(Beca JP.),
	(Lora P. GM.),
	(Escribar W., A.),
	(Bock PK.),
	(Papalia D.),
	(Núñez Rojas, N.),
	(Geneser F.),
	(Brown LM.),
	(Garces SB.),
	(NANDA Internacional.),
	(Brunner & Suddarth.),
	(Vial Larraín B.),
	(Kozier B.),
	(Alfaro-lefrive R.),
	(Marriner Tomey),
	(Perea QR.),
	(Narváez VPD.),
	(Rohlf RRS.),
	(Martínez-González MA.),
	(Netter FH.),
	(Moore. KL.D.),
	(Drake. RL.),
	(Guyton AC. Hall JE.),
	(Barret K. Barman S. Ganong),
	(Gal Iglesias B.),
	(Bohinski R.),
	(Nelson DL. Lehninger AL.),
	(Kozier, B),
	(Alfaro-lefrive, R),
	(Hernández-Aguado, I),
	(Álvarez, R),
	(Martínez-González),
	(Klainberg, M),
	(Zurro, MA; CPJF, GBJ),
	(Murray, PR),
	(Atías Martín, A),
	(Geneser, F),
	(Mosquera González, JM; Galdos Anuncibay, P),
	(Lorenzo Fernández, P),
	(Goodman, LS),
	(Porth, CM),
	(Braun, C),
	(Yáñez, A),
	(Netter, FH),
	(West, JB),
	(NANDA Internacional),
	(Brunner & Suddarth),
	(Vial Larraín, B),
	(Dillon, P),
	(Ahlbom-Alfredsson),
	(Villa-Moreno),
	(Ruiz-Murillo),
	(Moraga, R),
	(Burke, M. WM),
	(Chiavenato, I),
	(Robbins, S; Coulter, M),
	(Villalobos, J),
	(Fernández Sánchez, E),
	(Goleman, D),
	(Fuscoe, K; Garside, B; Prodromou, L),
	(Murphy, R),
	(Grice, T),
	(Álvarez Heredia, F),
	(Henao Robledo, F),
	(Mancera Fernández, M),
	(García, JA),
	(Díaz, VP),
	(Martínez, P),
	(Ruiz Reyes, G),
	(Del Cura, JL),
	(Giraldo Estrada, H),
	(Ángel Mejías, G),
	(Sánchez, DI),
	(Focks, C),
	(Marriner Tomey, A),
	(Meneghello Rivera, J),
	(Kliegman, RT),
	(Mattson, S),
	(Marino, P),
	(López Ramírez, JH),
	(Pérez Sánchez, A),
	(Pérez Sánchez, A; Donoso, SE),
	(Zurro, MA; CPJF; GBJ),
	(Tomey, AM),
	(Balderas),
	(Temes Montes, JL),
	(Wilson, D),
	(Jiménez Murillo, L),
	(National Association of Emergency Medical Technicians),
	(Johnson, B),
	(Rebraca, L),
	(Cornejo, EV; CMS),
	(Sapag Chian, N),
	(Zurro, M; Cano Pérez, A; Badia, JG),
	(Zurro, M; Jodar Solá, G),
	(Jaffe, M; Skidmore-Roth, L),
	(Klainberg, M; Holzemer, S; Leonard, M; Arnold, J),
	(Caballero Muñoz, E),
	(Lahee, F),
	(Maresch, W; Medenbach, O; Trochim, HD),
	(McClay, K),
	(Press, F; Siever, R),
	(Strahler, A),
	(Williams, H; Gilbert, CM; Turner, FJ),
	(Benton, MJ; Harper, DAT),
	(Berg, LR; Martin, DW; Solomón, EP; Villee, CA),
	(Villee, CA),
	(Mader, S),
	(Brown, TL; LeMay, HE; Bursten, BE; Burdge, JR),
	(Baldor, JA),
	(Moise, EE; Downs, FL),
	(Vance, EP),
	(Spiegel, MR; Moyer, RE),
	(Knight, HS; Knight, SR),
	(Lehmann, C),
	(Ayres, F),
	(Protter, MH; Protter, PE),
	(Swokowski, EW),
	(Swokowski, EW; Cole, JA),
	(Ballester-Arnal, R; Gil-Llario, MD),
	(Stanley, SM),
	(McCarthy, M; McCarten, J; Sandiford, H),
	(Marks, J),
	(Leithold, L),
	(Freedman, RA; Sears, FW; Young, HD; Zemansky, MW),
	(Raymond, A. S.; Jerry, S. F.),
	(Resnick, R; Halliday, D; Krane, KS),
	(Giancoli, DC),
	(Klein, C; Dana, J; Hurlbut, C),
	(Melgarejo, J),
	(Meléndez, B),
	(Allison, PA; Bottjer, DJ),
	(Miller, W (Ed.)),
	(Turner, D),
	(Larson, R; Hostetler, RP; Edwards, BH),
	(Díaz, JE; Ibarra, M; Leiva, R; Villarroel, L),
	(Alonso, M; Finn, E),
	(Brockbank, A; McGill, I),
	(Monte, M; Sebastiani, EM),
	(Francis, JT; Verhoogen, J),
	(Winkler, H),
	(Yardley, BWD),
	(Winter, J),
	(Sigurdsson, H; Houghton, B; Rymer, H; Stix, J; McNutt, S),
	(Tyrrell, GW),
	(Pérez, E),
	(Best, MG),
	(Crowther, J),
	(Billings, MP),
	(Marshak, S; Mitra, G.),
	(Lahee, FH),
	(Lisle, RJ),
	(Ragan, DM),
	(Niemeyer, H),
	(Freund, JE; Miller, I; Miller, M),
	(Devore, JL),
	(Montgomery, DC; Runger, GC),
	(Serway, RA; Jewett, JW),
	(Aguilar-Pérez, J),
	(Castellan, G),
	(Gaskell, DR),
	(Gurry, R; Darken, L),
	(Atkins, P.),
	(Upadhyaya, GS),
	(Albarède, F),
	(Dickin, AP),
	(Faure, G; Mensing, TS),
	(Fyfe, WS),
	(Garrels, RM; Christ, CL),
	(Hoefs, J),
	(Krauskopf, KB),
	(Misra, KC),
	(Rankama, K; Sahama, TG),
	(Davis, JC),
	(Rose, AW; Hawkes, HE; Webb, JS),
	(Moreno, T; Wibbons, W (Eds.)),
	(Marshak, S; Mitra, G),
	(Arche, A),
	(Boggs, S),
	(Hallam, A),
	(Krumbein, W; Sloss, L),
	(Nichols, G),
	(Pettijohn, F),
	(Pettijohn, F; Potter, PE; Siever, R),
	(Potter, P; Pettijohn, FJ),
	(Reading, HG),
	(Reineck, HE),
	(Tow, AV),
	(Tucker, ME),
	(Mott, RL),
	(Munson, B; Young, D; Okiishi, T),
	(Shames, IH),
	(Ocon, J; Tojo, G),
	(Vega, R; Christiansen, A),
	(Balmes, Z; González, G),
	(Cessany, D),
	(Ender-Egg, E; Aguilar, M),
	(González, A),
	(González, W),
	(Hernández, R; Fernández, C; Baptista, P),
	(Pérez, H),
	(Blanco, A),
	(Blázquez, D),
	(Wicander, R; Monroe, JS),
	(Anguita, F),
	(Catuneanu, O),
	(Davies, GF),
	(Sedimentological Impact),
	(Langmuir, CH; Broecker, W),
	(Murck, B; Skinner, B),
	(Poblet, J; Lisle, RJ),
	(Tarbuck, EJ; Lutgens, FK),
	(Vecoli, M; Clément, G; Meyer-Berthaud, B),
	(Wyllie, P),
	(Ranalli, C),
	(Fritz, WJ; Moore, JN),
	(Hallam, A; Freeman, WH),
	(Hedberg, HD),
	(Miall, AD),
	(Vera Torres, JA),
	(Einsele, G),
	(Middleton, GV; Southard, JB),
	(Reineck, HE; Singh, IB),
	(Stow, DAV),
	(Artur-Holmes, A),
	(Cantos-Figuerola, J),
	(Howell, BF),
	(Lozano, CL),
	(Milton, BD),
	(Mironov, VS),
	(Parasnis, DS),
	(Custodio, E; Llamas, R),
	(Davis, S; Wiest, R),
	(Derruau, M),
	(Muñoz-Jiménez, J),
	(Martínez de Pinzón, E; Tello, B),
	(Bold, HC; Alexopoulos, CJ; Delevoryas, T),
	(Sues, HD; Fraser, NC),
	(Vecoli, M; Clement, G; Meyer-Berthaud, B),
	(Jones, TP; Rowe, NP),
	(Willis, K; McElwain, J),
	(Barnes, JW),
	(McClay, KR),
	(Keller, EA),
	(Keller, EA; Blodgett, RH),
	(Strahler, AN),
	(Cereceda, P; Errazuriz, A; Lagos, M),
	(Peters, WC),
	(Laznicka, P),
	(Millán, A),
	(Tamayo, M),
	(Bunge, M),
	(Muñoz, I),
	(Mackenzie, FT),
	(Custodio, E; Llamas, MR),
	(Bustillo Revuelta, M; López Jimeno, C),
	(Chuvieco, E),
	(Dobrin, MB; Savit, CH),
	(Fontboté, L; Amstutz, GC; Cardozo, M; Cedillo, E; Frutos, J),
	(Frutos, J; Oyarzún, R; Pincheira, M),
	(Hartman, HL),
	(Koefoed, O),
	(Miguel, L de),
	(Orche, E),
	(Orellana, E),
	(Ruiz-Fuller, C; Peebles, LF),
	(Sabins, FF),
	(Sheriff, RE; Geldart, LP),
	(Instituto de Ingenieros de Minas de Chile),
	(Mirónov, VS),
	(Emery, X),
	(Kruger, P; Otte, C (Eds)),
	(Peters, W),
	(IGME),
	(Hoek, E; Brown, ET),
	(Jaeger, JC; Cook, NGW),
	(Juárez, E; Rodríguez, R),
	(Lambe, TW; Witman, R),
	(Arenas, FD; Masjuan, TG; Villanueva, MF),
	(Swokowski, E),
	(Vance, E),
	(Mori, C),
	(Cameron, EY),
	(Sominskii, IS),
	(Sobel, M),
	(Kindle, J),
	(Britton, J),
	(Leon, SJ),
	(Palma Sanz, F; Vasquez, P; Ortega, P),
	(Noble, B; Daniel, JW),
	(Hill, R),
	(Gerber, H),
	(Grossman, S),
	(Lang, S),
	(Lipschutz, S),
	(Larson, RE; Hostetler, RP),
	(Thomas, GB; Finney, RL),
	(Granville, WA),
	(Ayres, F; Mendelson, E),
	(Lehmann, CH),
	(Edwards, CH),
	(Williams, H; Turner, FJ; Gilbert, CM),
	(Watt, A),
	(Tipler, PA),
	(Sears, F; Zemansky, M; Young, H; Freedman, R),
	(Halliday, D; Resnick, R; Krane, KS),
	(Hewitt, P),
	(Serway, R; Faughn, J),
	(Brown, LT; Le May, E; Bursten, EB),
	(Rayner-Canham, G),
	(Moore, KJ; Wood, JS),
	(Petrucci, R; Harwood, W),
	(Brown, LT),
	(Chang, R),
	(Mortimer, EC),
	(Moore, J),
	(Matzlawick, P),
	(Chomsky, N),
	(Serafín, MT),
	(Mira, E; López, A),
	(Turner, JC),
	(Edwards, C; Penny, D),
	(Larson, R),
	(Zill, D),
	(Thomas, GB),
	(Kreyszig, E),
	(Marsden, J),
	(Marsden, J; Tromba, A),
	(Boyce, W; DiPrima, RC),
	(Proher, M; Morrey, C),
	(Spiegel, MR),
	(Scheaffer, RL; McClave, JT),
	(Mendenhall, W; Wackerly, D; Scheaffer, R),
	(Miller, I; Freund, JE; Johnson, RA),
	(Walpole, RE; Myers, RH),
	(Meyer, P),
	(Spiegel, M),
	(Bolfarine, H; Sandoval, MC),
	(Montgomery, DC),
	(Atkins, P),
	(Zemansky, M),
	(Levenspiel, O),
	(Alonso, P; Mochón, F),
	(Jordán, M; Pérez, A),
	(Martín, JL),
	(Samuelson, P; Nordhaus, W),
	(Joyanes, L),
	(Hecht, E),
	(Eisberg, R; Resnick, R),
	(Askeland, DR),
	(Avner, SH),
	(Nash, WA),
	(Koontz, H),
	(Certo, S),
	(Tanenbaum, A),
	(Lopez, A),
	(Amor, D),
	(Horngren, C; Harrison, W; Robinson, T),
	(Bosch, J),
	(Horngren, C),
	(Vargas, L),
	(Weston, F; Brigham, EF),
	(Van Horne, J),
	(Brealey, R),
	(Schall, L),
	(Edwards, C; Penney, D),
	(Simmons, G),
	(Campbell, SL; Haberman, R),
	(Zill, DG),
	(Serie Schaum),
	(Kreider, D; Kuller, R; Ostrerg, D),
	(O'Neill, R),
	(Sindermann, G; Harvey, AM),
	(Taha, HA),
	(Winston, WL),
	(Anderson, DR; Sweeney, DJ; Williams, TA),
	(Hillier, FS; Lieberman, GJ),
	(Mathur, K; Solow, D),
	(Shames, I),
	(Ocon; Tojo),
	(Vega B., R),
	(Larroulet Vignau, C),
	(Samuelson, P),
	(Parkin, M),
	(S., R; Daniel, L; Victor, A),
	(O’Sullivan, A; Sheffrin, SM),
	(Gutiérrez, L; Sepúlveda, J),
	(Wills, BA),
	(Kelly, RG; Spottiswood, DJ),
	(Rosenqvist, T),
	(Habashi, F),
	(Anon),
	(Cáceres, G; Joly, P),
	(Austin, GT),
	(Kirk-Othmer),
	(Buban, P; Shimitt, L),
	(Van Valkenburgh),
	(Gussow, M),
	(Giessen, D),
	(Schilling, D),
	(Stremler, F),
	(Blank, TL; Tarquin, JA),
	(DeGarmo, W; Sullivan, J; Bontadelli, E; Wicks, M),
	(Baca, G),
	(Dessler, G),
	(Gomez Mejias, L),
	(Chase, A; Aquilano, J; Jacobs, R),
	(Schroeder, RG),
	(Robbins, SP),
	(Rodríguez, D),
	(Gibson, J; Ivancevich, J),
	(Hill, C; Jones, G),
	(Hax, A; Majluf, N),
	(Kotler, Philip),
	(Kiely, Gerard),
	(Conesa Fernández-Vítora, Vicente),
	(Gómez Orea, Domingo y Oñate, Miguel),
	(Freeman, Harry M.),
	(Lagrega, Michael D., Buckingham, Phillip L. y Evans, Jeffrey C.),
	(Conesa Fernández, Vicente),
	(Coronado Maldonado, Margarito y Oropeza Monterrubio, Rafael),
	(Chile. Ministerio de Economía),
	(Fernández, Frank E. y Bird, Frank E.),
	(Handley, William),
	(Peralta, Abel),
	(Instituto Interamericano de Administración de Riesgos),
	(O'Neill, Robert),
	(Sindermann, Gerda y Harvey, Ana María),
	(Dornbusch, Rudiger y Fischer, Stanley),
	(Gamez Aiman, Consuelo),
	(Barro, Robert J.),
	(Dornbusch, Rudiger),
	(Miller, Roger),
	(Mankiw, N. Gregory),
	(Gutierrez, L. y Sepúlveda, J.),
	(Wills, B.A.),
	(Kelly, R.G. y Spottiswood, D.J.),
	(Cáceres, G. y Joly, P.),
	(Zarate, G.),
	(Austin, J.L.),
	(Echeverría, Rafael),
	(Maturana, Humberto),
	(Maturana, Humberto y Varela, Francisco),
	(Searle, Claude E. y Weaver, W.),
	(Vygotsky, Lev),
	(Bartsch, W.),
	(Mataix, Claudio),
	(Spotts),
	(Arias Paz),
	(Dawes, Chester),
	(Kosow),
	(Baros, Enrique),
	(Bobbio, Norberto),
	(Castán Tobeñas, José),
	(Fueyo Laneri, Fernando),
	(Humeres Magman y Otro),
	(Jellinek, George),
	(Messineo, Francesco),
	(Palomino Manchego y Velásquez Ramírez),
	(Rawls, John),
	(Samuelson, Paul y Nordhaus, William),
	(Johansen, Oscar),
	(Bravo, Juan),
	(Murdick, Robert),
	(Barros, Oscar),
	(Senn, James),
	(Ogata, K.),
	(Kuo, B.),
	(Rodríguez Mansilla, Darío),
	(French, Wendell L.),
	(Burke, W. Warner),
	(Schein, Edgar H.),
	(Guízar, Rafael),
	(Ralston, Anthony y Rabinowitz, Philip),
	(Martínez, Eliseo),
	(Korth, Abraham Silberschatz, Henry F.),
	(Date, C.J.),
	(Gazo Cervero, Alfonso),
	(Horngren, Charles),
	(Vargas V., Luis),
	(Sepúlveda, Fernando),
	(Superintendencia de Valores y Seguros),
	(Servicio de Impuestos Internos),
	(Jiménez Bermejo, Patricio),
	(Aracil, Javier y Gordillo, Francisco),
	(Hannon, Bruce y Ruth, Matthias),
	(Ruth, Matthias y Hannon, Bruce),
	(Kaplan, Daniel y Glass, Leon),
	(Von Bertalanffy, Ludwig),
	(Spire, Arnaud),
	(Yunus, Muhammad),
	(Martínez H., Eliseo),
	(Leroy Miller, Roger),
	(Sachs, Jeffrey y Larraín, Felipe),
	(Sapag Chain, Nassir),
	(Canada, John R.),
	(Fontaine, Ernesto R.),
	(MIDEPLAN),
	(Schroeder, Roger G.),
	(Kotler y Armstrong),
	(Solomon y Stuart),
	(Weston, Fred y Brigham, Eugene F.),
	(Van Horne, James),
	(Brealey, Richard),
	(Schall, Lawrence),
	(Diez de Castro, Luis),
	(Hill, Charles y Jones, Gareth),
	(Hax, Arnoldo y Majluf, Nicolás),
	(Sol, Patricio del),
	(Baldor, J.A.),
	(Downs, Moisés),
	(Vance, Elbridge P.),
	(Spiegel, Murray R.),
	(Knight, H.),
	(Lehmann, C.H.),
	(Ayres, Frank),
	(Protter, M.H.),
	(Swokowski, E.W.),
	(Swokowski, E.W. y Cole, A.),
	(Brown, Theodore L., LeMay, H. Eugene Jr., Bursten, Bruce E. y Burge, Julia R.),
	(Hewitt, Paul G.),
	(Grech M., Pablo),
	(Shaw, Milton),
	(Joyanes Aguilar, Luis),
	(Leithold, Louis),
	(Thomas, George Jr.),
	(Espinoza Ramos, Eduardo),
	(Nakos, George),
	(Grossman, S.),
	(Lay, D.),
	(Brown, Theodore L., Le May, H. Eugene Jr., Bursten, Bruce E., y Burge, Julia R.),
	(Deitel, H.M.),
	(Elmasri, Ramez & Navathe, Shamkan B.),
	(Mendelzon, Ale),
	(Larson, Ron; Hostetler, Robert P.; Edwards, Bruce H.),
	(Mochón, Francisco),
	(Samuelson, Paul & Nordhaus, William),
	(Pérez, Manuel J. y Amelia),
	(Mankiw, Gregory),
	(Sears, Francis W., Zemansky, Mark W., Young, Hugh D. & Freedman, Roger A.),
	(Serway, Raymond A. & Faughn, Jerry S.),
	(Resnick, Robert, Halliday, David & Krane, Kenneth S.),
	(Giancoli, Douglas C.),
	(García de Jalón, Javier),
	(Aho, Alfred V. & Hopcroft, John E.),
	(Joyanes Aguilar, Luis & Zahonero, Ignacio),
	(Hernández, Roberto),
	(Horowitz, Ellis, Sahni, Sartaj & Mehta, Dinesh),
	(Drozdek, Adam),
	(Hubbard, John),
	(Lafore, R),
	(Deitel, H. & Deitel, P),
	(Wirth, N),
	(Marsden-Tromba),
	(Stewart, James),
	(Lombardo, Josef V., Johnsony, Lewis O. & Short, W. Irwin),
	(Alvarado M., Sergio),
	(Straneo, S.L. & Consorti, R.),
	(Ministerio de Educación, Secretaría Técnica),
	(Spencer, Henry Cecil & Dygdon, John Thomas),
	(Tamez Esparza, Elías),
	(Sears, F. & Zemansky, M.),
	(Díaz, J.E., Ibarra, M., Leiva, R. & Villarroel, L.),
	(Alonso, M. & Finn, E.),
	(Resnick, D., Halliday, D. & Krane, K.),
	(Giancoli, Douglas),
	(Baca, Gabriel),
	(Del Sol, Patricio),
	(Ross, S.),
	(Aguilar Peris, José),
	(Castellan, Gilbert),
	(Gaskell, David R.),
	(Gurry, R. & Darken, L.),
	(Zemansky, Mark),
	(Upadhyaya, G.S.),
	(Sears, F. & Zemansky, M., Young, H. & Freedman, R.),
	(Serway, R. & Beichner, R.),
	(Hecht, E.),
	(Guíñez, V., Labarca, R. & Martínez, M.),
	(Zill, D.),
	(Ayre, F),
	(Weitzenfeld, Alfredo),
	(Booch, Grady; Rumbaugh, James; Jacobson, Ivar),
	(Pressman, R.S.),
	(Laudon, Kenneth & Laudon, Jane),
	(García Bravo, Daniel),
	(Mano, M. Morris),
	(Tocci, Ronald J. & Widmer, Neal S.),
	(Floyd, Thomas L.),
	(Burden, R. & Douglas, J.),
	(Freund, J.E.; Miller, I. & Miller, M.),
	(Devore, J.L.),
	(Meyer, P.L.),
	(Montgomery, D.C. & Runger, G.C.),
	(Hibbeler, Russell C.),
	(Beer, Ferdinand P.),
	(Askeland, Donald R.),
	(Schaffer, J.),
	(Larman, Craig),
	(Monk, Simon),
	(Blum, Jeremy),
	(Castaño, Juan & González, Felipe),
	(Angulo Usategui, José M.; Romero Yesa, Susana & Angulo Martínez, Ignacio),
	(Angulo Usategui, José M.),
	(Mano, M. Morris; Kime, Charles R.),
	(Mott, Robert L.),
	(Munson, B.; Young, D. & Okiishi, T.),
	(Shames, Irving H.),
	(Ocon & Tojo),
	(Taha, H.A.),
	(Barahona Droguett, Manuel),
	(Winston, W.),
	(Hillier, F. & Liberman, G.J.),
	(Robbins, Stephen P. & Coulter, Mary),
	(Koontz, Harold & Weihrich, Heinz),
	(Hernández, Sergio & Rodríguez),
	(Chiavenato, Idalberto),
	(Nilsson, Nils),
	(Turing, Alan M.),
	(Russell, Stuart & Norvig, Peter),
	(Comer, Douglas),
	(Kurose, Jim & Ross, Keith),
	(d.school),
	(Seelig, Tina),
	(Gómez Orea, Domingo & Oñate, Miguel),
	(Lagrega, Michael D.; Buckingham, Phillip L. & Evans, Jeffrey C.),
	(Coronado Maldonado, Margarito & Oropeza Monterrubio, Rafael),
	(Jordán Barahona, José Manuel),
	(Valls, Mario),
	(Gómez, M.),
	(Sommerville, Ian),
	(Pressman, Roger),
	(Cruz del Castillo, Cinthia; Olivares Orozco, Socorro & González García, Martín),
	(Pfleeger, S.L.),
	(McConnell, Steve),
	(Martin, Robert C.),
	(Stevens, Perdita),
	(Barrientos, A.; Peñín, L.F.; Balaguer, C. & Aracil, R.),
	(Creuss, Antonio),
	(Porter, M.),
	(Hax, A. & Majluf, N.),
	(Thompson & Strickland),
	(Urbany, Joel E. & Davis, James H.),
	(Anderson, J.; Narus, J. & Van Rossum, W.),
	(Miranda Olivan, A.),
	(Osterwalder, Alexander),
	(Laudon, K. y Laudon, J.),
	(Barrientos, A., Peñín, L.F., Balaguer, C. y Aracil, R.),
	(Bolton, W.),
	(Sommerville, I.),
	(Pressman, R.),
	(McConnell, S.),
	(Martin, R.C.),
	(Stevens, P.),
	(Behrouz, F.),
	(Tanenbaum, A.),
	(Stallings, W.),
	(Comer, D.),
	(García de Jalón, J.),
	(Espinela, E.F.),
	(Adelstein, T.),
	(Del Sol, P.),
	(Curto Díaz, J.),
	(Hernández Orallo, J., Ramírez Quintana, M.J. y Ferri Ramírez, C.),
	(Bandel, D. y Napier, R.),
	(Webb, J.),
	(Korth, H.F. y Silberschatz, A.),
	(Laundon, K.),
	(Andreu, R.),
	(González, C.),
	(Muñoz R., C.),
	(Taborga, H.),
	(Hernández, R.),
	(Quezada, N.),
	(Condemarin, G.),
	(Calero, A.),
	(Núñez Delgado, P.),
	(Gessel, A.),
	(Papalia, D.),
	(Toledo, V.),
	(Sharp, M.),
	(Travers, R.),
	(Hughes, J., Stephenson, H., y Dummett, P.),
	(Dudeney, G. y Hockly, N.),
	(Motteram, G.),
	(Harmer, J.),
	(Pavez, K. y Roman, C.),
	(Díaz, I., López, J., Cáceres, M., Barros, C., y Hinojo, F.),
	(Oxford, R.),
	(Brown, H.D.),
	(Aarts, B.),
	(Yule, G.),
	(Fries, C.),
	(Katamba, F.),
	(Tallerman, M.),
	(Blekyarov, T.),
	(Carstair-McCarthy, A.),
	(Burton-Roberts, N.),
	(Newson, M., et al.),
	(Widdowson, H.G.),
	(Azar, B.),
	(Hewings, M.),
	(Ur, P.),
	(Spratt, M., Pulverness, A., y Williams, M.),
	(Centro de Perfeccionamiento, Experimentación e Investigaciones Pedagógicas),
	(López, A.),
	(Novara, D.),
	(Rulicki, S.),
	(Steiner, C.),
	(Stevens, J.),
	(Rodríguez, C.),
	(Díaz, C.),
	(Peters, R.),
	(Gutiérrez, F.),
	(Rundell, M.),
	(Hornby, A.S., Turnbull, J., Wehmeier, S., y McIntosh, C.),
	(Jones, D.),
	(Vince, M.),
	(Wright, A.),
	(Murado, J.),
	(Larsen-Freeman, D.),
	(Carretero, M., Bennet, N., Järvinen, A., Pope, M., y Ropo, E.),
	(Coll, C.),
	(Coll, M., Palacios, J.),
	(Alvares, A.),
	(Araújo, J.B.),
	(Ausubel, D.),
	(Bruner, J.),
	(Daud, B., Grahome, F.),
	(Good, T.L., Brophy, J.),
	(Gardner, H.),
	(Hagarty, S., Pocklington, K.),
	(Klinger, C.),
	(Loughlin, C.E.),
	(Pilar, J., y cols.),
	(MINEDUC),
	(Pérez, M.R., Gallego, B.R.),
	(Poeydomenge, M.),
	(Pozo, J.I.),
	(Dewey, J.),
	(Gimeno, J.),
	(Real Academia Española),
	(Fuentes, J.),
	(Condemarín, M., Medina, A.),
	(Seuss, T.),
	(Bibliográfica Internacional),
	(Steiner, R., Gralhi, U.),
	(Seuss, Dr.),
	(Moss, A., Stott, J.),
	(Munsch, R.),
	(Sneed, B.),
	(Tilbury, C., Clementson, T.),
	(Stephenson, H.),
	(Vice, M.),
	(Baker, A.),
	(Finch, D., Ortiz, H.),
	(Hooke, R., Rowell, J.),
	(Hancock, M.),
	(Baker, A., Goldstein, S.),
	(Brown, H.),
	(Richards, J., Rodgers, T.),
	(Spratt, M., Pulverness, A., Williams, M.),
	(Vale, D., Feunteun, A.),
	(Estándares de la Profesión Docente),
	(Argondizzo, C.),
	(Pavez, K., Seguel, R.),
	(Gilliland, B., Pavez, K., Muñoz, A.),
	(Novara, D., Ballester, C.),
	(López, A., Parada, A., Simonetti, F.),
	(Rulicki, S., Cherny, M.),
	(Stevens, J.O.),
	(Reale, G., Antiseri, D.),
	(Aranguren, J.L.),
	(Cazares, G., Morales, F., Lozano V., y Camacho, L.),
	(Hernández, A.),
	(García, A.),
	(Form, E.),
	(Maritain, J.),
	(Cobo, J.),
	(Tobón, S.),
	(Bloom, B.),
	(Castillo, S. y Cabrerizo, J.),
	(Medina, A. y Condermarin, M.),
	(Lafourcade, P.),
	(Stobart, G.),
	(Castilla, S. (Coord.)),
	(Hein, A. y Taut, S.),
	(Monereo, C. (Coord.)),
	(Guerra, S. y Ángel, M.),
	(Keesing, R.),
	(Burke, M.),
	(Crapo, R. H.),
	(Garraty, J. A. y Carnes, M. C.),
	(Holden, R. H. y Zolov, E.),
	(Kirk, G. y Okazawa-Rey, M.),
	(Tindall, G. y Shi, D. E.),
	(Savage, A. y Shafiei, M.),
	(Tilbury, A., Clementson, T., Hendra, L., y Rea, D.),
	(Alexander, L.),
	(Hashemi, L. y Thomas, B.),
	(Finch, D. y Ortiz, H.),
	(Hooke, R. y Rowell, J.),
	(Baker, A. y Goldstein, S.),
	(Puchta, H., Williams, M.),
	(Scrivener, J.),
	(Hearn, I., Garcés, A.),
	(Suárez, M.),
	(Vega-Hazas, J.),
	(Saracostti, M.),
	(Pontificia Universidad Católica de Chile, Teleduc),
	(Bohm, W., Schiefelbein, E.),
	(Stainback, S., Stainback, W.),
	(Torres, J.),
	(Casanova, M.),
	(Brown, D.),
	(Santos, M.),
	(Rabley, S.),
	(Christopher, D.),
	(McDowall, D.),
	(Crapo, R.H.),
	(Storry, M.),
	(Storry, M., Childs, P.),
	(Davis, J., Rhonda, L.),
	(Vince, M),
	(Savage, A., & Mayer, P),
	(Brown, D),
	(Harmer, J),
	(Akmajian, Adrian, et al),
	(Bailey, Kathleen M., & Nunan, David),
	(Blake, N., & Moorhead, J),
	(Celce-Murcia, Marianne, & Larsen-Freeman, Diane),
	(Crane, Ben L., Yeager, Edward, & Whitman, Randal L),
	(Dulay, Heidi, Burt, Marina, & Krashen, Stephen),
	(Ellis, Rod),
	(Finch, Geoffrey),
	(Lewis, Michael),
	(Lightbown, Patsy, & Spada, Nina),
	(Littlewood, William),
	(Nunan, David),
	(O’Grady, William, et al),
	(Richard-Amato, Patricia),
	(Richards, Jack, & Lockhart, Charles),
	(Richards, Jack, Platt, John, & Weber, Heidi),
	(Richards, Jack C., & Renandya, Willy A),
	(Spolsky, Bernard),
	(Wright, Tony),
	(Brown, H),
	(Ur, P),
	(Puchta, H., & Williams, M),
	(Vale, D., & Feunteun, A),
	(Gilliland, B., Pavez, K., & Muñoz, A),
	(Cpeip),
	(Preiss, D., et al),
	(Schmelkes, C),
	(Samaya, J),
	(Flick, U),
	(American Psychological Association),
	(Sierra Bravo, R),
	(Ilabaca, J. S),
	(Varios Autores),
	(Gilbert, S., & Gubar, S),
	(Mack, M., Ed),
	(Baym, N., et al., Ed),
	(Ferguson, M. W., Salter, M., & Stallworthy, J., Ed),
	(Brown, H. Douglas),
	(Harmer, Jeremy),
	(Scrivener, J),
	(Wallace, M),
	(Spratt, M., Pulverness, A., & Williams, M),
	(Swift, Jonathan),
	(O’Dell, F., & Broadhead, A),
	(Savage, Alice, & Shafiei, Masoud),
	(Hedge, Tricia),
	(Hill, & Jones),
	(Doff, A., & Goldstein, B),
	(Savage, A., & Shafiei, M),
	(Hedge, T),
	(Jones, D),
	(Hooke, R., & Rowell, J),
	(Kachru, B),
	(Neumann, D. A),
	(Testut, L., & Latarjet, A),
	(Lodish, H),
	(Cromer, A),
	(Brown, Le May, & Bursten),
	(Peña, M),
	(Testut, L. & Latarjet, A),
	(Nordin, M. & Frankel, H. V),
	(Horton, R. H),
	(Guyton, A. & Hall, J. E),
	(Guix, X),
	(Porth, C),
	(López, J. & Fernández, A),
	(Fejerman, N. & Fernández, E),
	(Herrera, O. & Quezada, A),
	(Berman, A. & Snyder, S),
	(Brotzman, S. & Manske, R),
	(Milton, S),
	(Boyling, J. & Gwendolen, J),
	(Schonhaut, L. & Aseff, M),
	(Palmer, L. & Epler, M),
	(Ahlbom, A., Alfredsson, L., Alfven, T., & Bennet, A),
	(Goic, A. & Chamorro, G),
	(Goodman & Gilman),
	(Cameron, M),
	(Cristancho, W),
	(Prentice, W),
	(Lederman, E),
	(Cura, J. L., Pedraza, S. & Gayete, A),
	(Rodríguez Machado, M),
	(García, J., Jiménez, F., Arnaud, M., Ramírez, Y., & Lino, L),
	(Shumway-Cook, A. & Woollacott, M),
	(Henao, F),
	(Davies, P),
	(Hamill, J., Knutzen, K., & Derrick, T),
	(Knight, H),
	(Lehmann, C. H),
	(Protter, M. H),
	(Swokowski, E. W),
	(Swokowski, E.W., Cole, R. A.),
	(Schunk, D. H.),
	(Castillo Inzulza, G.),
	(Seron Muñoz, J. & Aguilar Villagrán, J. M.),
	(Blanco, A.),
	(Rueda, A. & Otros),
	(Strahler, A.),
	(Rogers, J.W. & Adams, A.S.),
	(Meléndez, B. & Fuster, J.),
	(Brown, T. L., LeMay, H. E. Jr., Bursten, B. E., & Burge, J. R.),
	(Hewitt, P. G.),
	(Baldor, J. A.),
	(Downs, M.),
	(Vance, E. P.),
	(Spiegel, M. R.),
	(Espinoza Ramos, E.),
	(Nakos, G.),
	(Leithold, L.),
	(Thomas, G.),
	(Gil, F. & León, J. M.),
	(Patterson, K., Grenny, J., McMillan, R., & Switzler, A.),
	(Joyanes Aguilar, L.),
	(Larson, R., Hostetler, R., & Edwards, B.),
	(Lombardo, J. V., Johnson, L. O., & Short, W. I.),
	(Alvarado M., S.),
	(Straneo, S. L. & Consorti, R.),
	(Ministerio de Educación de Chile),
	(Spencer, H. C. & Dygdon, J. T.),
	(Tamez Esparza, E.),
	(Sears, F. W. & Zemansky, M. W.),
	(Serway, R. A. & Faughn, J. S.),
	(Resnick, R., Halliday, D., & Krane, K.),
	(Giancoli, D. C.),
	(Dana),
	(Ford, W.),
	(Heinrich, E.),
	(Susaeta, E.),
	(Skoog, D. A., West, D. M., Holler, F. J.),
	(Hamilton, L., Simpson, S., & Ellis, D.),
	(Willar, H. H., Merrit, L. L. Jr., Dean, J. A., Settle, F. Jr.),
	(Day, R. A. Jr., & Underwood, A. L.),
	(Morrison, J. D.),
	(Rakoffy, H., & Rose, N. C.),
	(Solomons, T. W. G.),
	(Marsden, J. E., & Tromba, A. J.),
	(Stewart, J.),
	(Guíñez, V., Labarca, R., & Martínez, M.),
	(Ayre, F.),
	(Sears, F. W., Zemansky, M. W., Young, H. D., & Freedman, R. A.),
	(Díaz, I. E., Ibarra, M., Leiva, R., & Villarroel, L.),
	(Alonso, M., & Finn, E. J.),
	(Mechón, F.),
	(Samuelson, P. A., & Nordhaus, W. D.),
	(Pérez, M. J., & Pérez, A.),
	(Aguilar Peris, J.),
	(Castellan, G.),
	(Gaskell, D. R.),
	(Gurry, R., & Darken, L.),
	(Zemansky, M. W.),
	(Upadhyaya, G. S.),
	(Jones, G. R., & George, J. M.),
	(Hernández Rodríguez, S.),
	(Chiavenato, I.),
	(Askeland, D. R.),
	(Avner, S. H.),
	(Sears, F., Zemansky, M., Young, H., & Freedman, R.),
	(Alonso, M., & Finn, E.),
	(Serway, R., & Beichner, R.),
	(Mott, R. L.),
	(Munson, B., Young, D., & Okiishi, T.),
	(Shames, I. H.),
	(Ocon, J., & Tojo, M.),
	(Burden, R., & Douglas, J.),
	(Freund, J. E., Miller, I., & Miller, M.),
	(Devore, J. L.),
	(Meyer, P. L.),
	(Montgomery, D. C., & Runger, G. C.),
	(Bird, R. B., Stewart, W. E., & Lightfoot, E. N.),
	(Cengel, Y. A.),
	(Szekely, J., & Themelis, N. J.),
	(Levenspiel, O.),
	(Le Maistre, S., & Lewis, C.),
	(Gutiérrez-Jairne Sepúlveda, L.),
	(Austin, L., & Concha, F.),
	(Hibbeler, R. C.),
	(Beer, F. P.),
	(Kelly, E., & Spottiswood, D.),
	(Himmelblau, D., & Bischoff, K.),
	(Bronkala, W. J., et al.),
	(Kelly, E. G., & Spottiswood, D. J.),
	(Lawyer, I. E.),
	(Cunningham, O., & Mohamed, S.),
	(Taha, H. A.),
	(Barahona Droguett, M.),
	(Winston, W. L.),
	(Hillier, F., & Liberman, G. J.),
	(Gajardo, A., Mendoza, J., López, M., & Carrasco, R.),
	(Shewmon, P.),
	(Reed-Hill, R. E.),
	(Guy, A. G.),
	(Smith, W. F.),
	(Kiely, G.),
	(Conesa Fernández-Vítora, V.),
	(Gómez Orea, D., & Oñate, M.),
	(Freeman, H. M.),
	(Lagrega, M. D., Buckingham, P. L., & Evans, J. C.),
	(Conesa Fernández, V.),
	(Coronado Maldonado, M., & Oropeza Monterrubio, R.),
	(Jordán Barahona, J. M.),
	(Valls, M.),
	(Aguirre, J.),
	(Byors, L.),
	(Gómez, L.),
	(Muñoz, O.),
	(Gallardo, M.),
	(Lobos, J.),
	(Ulric, D., & Brockbank, W.),
	(Costa, M., & López, E.),
	(Cooper, D., Robertson, I., & Tinline, G.),
	(Gil, I., Ruiz, L., & Ruiz, J.),
	(Werther, W.),
	(De La Plaza, J.),
	(Kossen, S.),
	(Arias, F.),
	(Jaime, & Cabrera, Á.),
	(Shames, I. B.),
	(Ocon, & Tojo),
	(Vega B., R.),
	(Baca Urbina, G.),
	(Blank, L., & Tarquin, A.),
	(Riggs, J. L.),
	(Sapag, N., & Sapag, R.),
	(Crace, A., & Wileman, R.),
	(Dieter, G.),
	(Allis Chalmers),
	(Austin, L. O., et al.),
	(Weiss, N. L.),
	(Wills, B. A.),
	(Crozier, R. D.),
	(Domic, M. E.),
	(Biswas, A., & Davenport, W.),
	(Davenport, W., & Partelpoeg, E.),
	(Peters, A.),
	(Peacey, J. G.),
	(Coudurier, L., Hopkins, D., & Wilkomirsky, I.),
	(Rosenqvist, T.),
	(Habashi, F.),
	(Ray, H., & Ghosh, A.),
	(Butts, A.),
	(Marsden, J., & House, I.),
	(Fine, A.),
	(American Water Works Association),
	(Nalco Chemical Company),
	(Metcalf & Eddy),
	(Sánchez, M., Vergara, F., & Castro, S.),
	(De Nevers, N.),
	(Fernández, F. E., & Bird, F. E.),
	(Handley, W.),
	(Peralta, A.),
	(Dorf, R. D.),
	(Kuo, B. J.),
	(Sepúlveda, L. E., & Gutiérrez, L.),
	(A.J.),
	(Kolb, D. A., Rubin, I. M., & McIntyre, J. M.),
	(Himmelblau, D.),
	(Curso Panamericano de Metalurgia Extractiva),
	(Walpole, R., & Myers, R.),
	(CIMM),
	(Aranguren, J. L.),
	(Covey, S.),
	(De Saint-Exupéry, A.),
	(Echeverría, R.),
	(Fisher, R.),
	(Jarillo, C.),
	(Hax, A., & Majluf, N.),
	(Garrido, S.),
	(Francés, A.),
	(Reghezza, A.),
	(Instituto Tecnológico GeoMinero de España),
	(Sepúlveda, J., & Gutiérrez, L.),
	(Mular, A. L., & Bhappu, R. B.),
	(Avendaño, C.),
	(Gutiérrez, L., & Aguilar, O.),
	(Millán, U. A.),
	(Mular, A.),
	(Hernández Sampieri, R.),
	(Lehmann, C. H.),
	(Ayres, F.),
	(Protter, M. H.),
	(Swokowski, E. W.),
	(Swokowski, E. W., & Cole, A.),
	(Brown, T. L.,LeMay, H. E.,Bursten, B. E.,Burge, J. R.),
	(Fernández Collado, C.),
	(Papalia, D., Wendkos, S., & Feldman, R. D.),
	(Papalia, D., & Wendkos, S.),
	(Hartman, H.),
	(Hustrulid, W., Kuchta, M., & Martin, R.),
	(Hustrulid, W., & Bullock, R. L.),
	(Brown, T. L., LeMay, H. E., et al.),
	(Luzadder, W. J., & Duff, J. M.),
	(Jensen, C. H., & Duff, J. M.),
	(Errázuriz, A. M., & González, J. I.),
	(Raisz, E.),
	(Hidalgo, M.),
	(Lahee, F.),
	(Williams, H., Turner, F. J., & Gilbert, C. M.),
	(Press, F., & Siever, R.),
	(Maresch, W., Medenbach, O., & Trochim, H. D.),
	(Sears, F. W., & Zemansky, M. W.),
	(Serway, R. A., & Faughn, J. S.),
	(Resnick, R., Halliday, D., & Krane, K. S.),
	(Mochón, F.),
	(Laznicka, P.),
	(Hurlbut, C. S.),
	(Dana, E. S., & Ford, W. E.),
	(Marsden, J. E., & Tromba, A.),
	(Young, H. D., & Freedman, R. A.),
	(Díaz, J. E., Ibarra, M., Leiva, R., & Villarroel, L.),
	(Pérez, E.),
	(Montes de Oca, M.),
	(Alcántara García, D.),
	(Kissam, P.),
	(Resnick, D., Halliday, D., & Krane, K.),
	(Serway, R. A., & Beichner, R. J.),
	(Sitter, L. U.),
	(Hobbs, B. E., Means, W. D., & Williams, P. F.),
	(Hartman, H. (Ed.)),
	(Hustrulid, W., & Bullock, L.),
	(Wolf, P. R., & Brinker, R. C.),
	(Berger, P., & Luckmann, T.),
	(Lindgren, H. C.),
	(Zúñiga Burmester, R.),
	(Beal, G. M.),
	(López J., C.),
	(Gustafssono, R.),
	(Ocon, L., & Tojo, A.),
	(Vega, R. B.),
	(Hillier, F., & Lieberman, G. J.),
	(Orche, E.),
	(Alfaro, M.),
	(Kennedy, J. B., & Neville, A. M.),
	(CEMA),
	(Novitzky, A.),
	(Kennedy, B. A.),
	(Noakes, M., & Lanz, T.),
	(López, C., López, E., Manglano, S., & Toledo, J.),
	(Vallejo, J., & Latorre, E.),
	(Neyth, D., & Latorre, E.),
	(Díaz, G., & Latorre, E.),
	(Becerra, C., & Latorre, E.),
	(Parra, F., & Olmos, H.),
	(Núñez, M., & Latorre, E.),
	(Ortíz, C., & Fribla, M.),
	(Guaita, E., & Arias, C.),
	(Marín, G., & Latorre, E.),
	(Astudillo, C., & Santibañez, E.),
	(Rojas, L., & Santibañez, E.),
	(ENAEX),
	(Campos, V., & Marcos),
	(Molina Suazo, G.),
	(Ireco),
	(Gustafsson, R.),
	(Langefors, U.),
	(Instituto Geológico y Minero de España),
	(n.d.),
	(Abarca Huerta, H.),
	(Chávez Gavilán, W.),
	(Atlas Powder Company),
	(Chile. Dirección General de Movilización Nacional),
	(Carrizo Craig, J.),
	(Sepúlveda Ceroni, S.),
	(Abarca Flores, C.),
	(Mercado Zamorano, L.),
	(Lobos López, A.),
	(Moraga Cordero, A.),
	(Montealegre Ubillo, A.),
	(Bustos Choppelo, L.),
	(Hernández, S.),
	(Yañez Garín, E.),
	(Gillies, A. D. S.),
	(Superintendencia Planificación e Ingeniería),
	(Olivares Massardo, L.),
	(González Ruiz, C., & Muñoz Castro, N.),
	(Donoso Figueroa, P., & Muñoz Castro, N.),
	(Valencia Pérez, C., & Olmos Naranjo, H.),
	(Collao Vega, E., & Santibañez Castro, E.),
	(Aguirre Sarria, C., & Olmos Naranjo, H.),
	(Bird, F. E., & Fernández, F. E.),
	(Aguirre Cortés, E., Nick Carvajal, J., & Godoy Galleguillos, R.),
	(Quinteros Estrada, S., & Godoy Galleguillos, R.),
	(Chávez Cayo, J., & Godoy Galleguillos, R.),
	(Arteaga, R., et al.),
	(Millán, A.),
	(Bustillo, M., & López, C.),
	(Bustillo Revuelta, M., & López Jimeno, C.),
	(Chuvieco, E.),
	(Dobrin, M. B., & Savit, C. H.),
	(Frutos, J., Oyarzún, R., & Pincheira, M.),
	(Hartman, H. L.),
	(Peters, W. C.),
	(Fontboté, L., Amstutz, G. C., Cardozo, M., Cedillo, E., & Frutos, J.),
	(Koefoed, O.),
	(Legua Olivares, S.),
	(Miguel, L. de),
	(Mirónov, V. S.),
	(Orellana, E.),
	(Parasnis, D. S.),
	(Emery, X.),
	(Isaaks, E., & Srivastava, R.),
	(Henríquez, E., & Navea, J.),
	(Vilches, R., & Navea, J.),
	(Hustrulid, W. A., & Kuchta, M.),
	(Lane, Kenneth),
	(Norambuena, M., & Santibañez, E.),
	(Espinoza, J., & Olmos, H.),
	(Latorre, A., Carvajal, K., & Riffo, V.),
	(Cisternas, V., & Olmos, H.),
	(Olivares, V., & Latorre, E.),
	(Valenzuela, R., & Fribla, M.),
	(Darling, P.),
	(Hustrulid, W. A., & Bullock, R. L.),
	(Villaescusa, E.),
	(Pavez Miqueles, O.),
	(Astorga, Flores, & Ángel),
	(Currie, J. M.),
	(Sutulov, A.),
	(Esteban, D.),
	(Arenas Fuentes, A.),
	(Cáceres Arenas, G.),
	(Vergara Parra, C.),
	(Bockris, J. O'M., & Reddy, A. K. N.),
	(Project Management Institute),
	(Ajenjo, A. D.),
	(Briceño, P.),
	(Ahuja, H. N., & Walsh, D.),
	(Chase, R., Jacobs, F. R., & Aquilano, N. J.),
	(González López, L.),
	(Huerta, J. J., & Rodríguez, G.),
	(Mine and Mill Equipment Cost),
	(Runge, I. C.),
	(Gertsch, R. E., & Bullock, R. L.),
	(Coss, R.),
	(Banks, J., & Carson, J.),
	(Pardo, L., & Valdés, T.),
	(Hillier, F., & Lieberman, G.),
	(Lagos, G.),
	(Ribeiro, L.),
	(Hernández Sampieri, R. et al.),
	(Netter, F. H.),
	(Drake, R. L., Vogl, W., & Mitchell, A. W. M.),
	(Fuscoe, K., Garside, B., & Prodromou, L.),
	(Ees, P., Sparks, F., & Rees, C.),
	(Brown, L. T., Le May, E. Jr., & Bursten, E. B.),
	(Chang, R.),
	(Lolas Stepke, F.),
	(Fawcett, D. W.),
	(Junqueira, L. C., & Carneiro, J.),
	(Gartner, L. P., & Hiatt, J. L.),
	(Geneser, F.),
	(Ross, M. H., & Pawlina, W.),
	(Hernández, Á. G.),
	(Muñiz, R. G.),
	(Martínez, M. A.),
	(Perea Quesada, R.),
	(Restrepo, H.),
	(Mathews, C.),
	(Guyton, C. G., & Hall, I. E.),
	(Ganong, W.),
	(Berne, R., Levy, M., & Koeppen, B.),
	(Jay, J.),
	(Jay, J., Loessner, M., & Golden, D.),
	(Barrera, M. G.),
	(De Girolamo, D. H.),
	(Cornejo, V., & Cruchet, S.),
	(Mahan, L.),
	(Fernández, A., & Navarro, K.),
	(Wenger, H. A., & Green, H. J.),
	(Higashhida),
	(López Chicharro, J., & López Mojare, L. M.),
	(Goic, G., & Chamorro, A.),
	(Henry, M., Jane, W.),
	(Longo, D. L.),
	(Guyton, A.),
	(Ganong, W. F.),
	(Eroles et al.),
	(Martínez-González, M. Á.),
	(Álvarez, R., & Kuri-Morales, P. A.),
	(Hernández Ávila, M., & Lazcano Ponce, E.),
	(Piedrola Gil, G.),
	(Martínez González, M. Á.),
	(Cheftel, J. G., & cols.),
	(Potter, N.),
	(Fernández, P. L., & cols.),
	(Mestres Miralles, C.),
	(Florez, J),
	(Gilman, A. L.),
	(Mahan, L., & cols.),
	(Bueno, M., Sarria, A., & Pérez-González, J. M.),
	(Kathleen, L., & Escott-Stump, S.),
	(Henry, M., Jane, W., & cols.),
	(Millán, J. C.),
	(Gil),
	(Rodota, L., & Castro, M. E.),
	(Riella, C., & Martins, C.),
	(Moreno Altamirano, L., Cano Valle, F., & García Romero, H.),
	(Tejada, B. D.),
	(West, J. B.),
	(Patiño Restrepo, J. F),
	(Tipton, C. M.),
	(Forsythe, T. J., & Tucker, P. H.),
	(Mahan, L., & Escott-Stump, S.),
	(Pinto, R. J.),
	(Díaz, P.),
	(Colombo, M., Raimann, E., & Cornejo, V.),
	(Burke, L.),
	(Ganong, W. F),
	(González, W. J),
	(Hernández Sampieri, R),
	(Restrepo, H),
	(Schwarcz, R., Fescina, R., & Duverges, C),
	(Oyarzún, E),
	(González Merlo, J., Lailla, J. M., Fabre, E., & González, E),
	(Walker, C),
	(Moore, K. L),
	(Drake, R. L., Vogl, W., & Mitchell, A. W. M),
	(Netter, F. H),
	(Saladín, K. S),
	(Lodish, H., Berk, A., & Matsudaira, P. T),
	(Nelson, D. L., & Cox, M. M),
	(Brown, L., & May, B),
	(Petrucci, R),
	(Kottow, M),
	(Beca, J. P., & Astete, C),
	(Voet, D., & Voet, J. G),
	(Lodish, H., et al),
	(O’Neill, R),
	(Papalia, D. E),
	(Frías Osuna, A),
	(Piédrola Gil, G),
	(Milton, J. Susan),
	(Sadler, T. W),
	(Moore, K),
	(Cochard, L),
	(Mackenna),
	(Gratacos, E),
	(Martínez González, M),
	(Fox, S),
	(Costanzo, L),
	(Gal, B., López, M., Martín, A., Prieto, J),
	(Hall, J),
	(Murray, P. R., Rosenthal, K. S., Pfaller, M. A),
	(Montero, L),
	(Berek y Novak),
	(Goic, A),
	(Lorenzo, P),
	(Mosquera, G),
	(Braun, C. A., Anderson, C. M),
	(Mattson Porth, C),
	(Ceriani, J),
	(Tapia, J),
	(Cloherty, J., Eichenwald, E., Hansen, A. & Stark, A),
	(Gomella, T),
	(Fernández, P., Caballero, E. & Medina, G),
	(Schwarcz, R., Fescina, R. & Duverges, C),
	(González Merlo, J., Lailla, J. M., Fabre, E. & González, E),
	(Berman, A. J. & Snyder, S),
	(Jensen, S),
	(Alligood, M. R. & Tomey, A. M),
	(Caballero, E),
	(Tapia, J. & Ventura-Junca),
	(García, J. A. y otros),
	(Calais-Germain, B. & Vives, N),
	(Cuello, M),
	(López Ramírez, J),
	(Palma, A., Taboada, P. & Nervi, F),
	(Rincón, S),
	(Tapia, J & Ventura-Junca),
	(García, J. A. & otros),
	(Hernández Sampieri, R. & otros),
	(Castelo-Branco),
	(Molina, R),
	(Hernández-Aguado, I & otros),
	(Cosialls, D),
	(Mompart-Tomey, A),
	(Hernández-Aguado, I. & otros),
	(John P. Cloherty, Ann R. Stark),
	(Jaeger, W),
	(Cirigliano, G),
	(Orrego, S),
	(Maturana, H),
	(Selsam, H),
	(Althusser, L),
	(Apple, M),
	(Bourdieu, P),
	(Cerutti G., H),
	(González R., A),
	(Hegel, G),
	(Munizaga A., R),
	(Maritain, J),
	(Jasper, K),
	(Freire, P),
	(Cassany, D),
	(CondeMarín, M),
	(Pérez Riffo, M),
	(RAE),
	(Ivern, A),
	(Ullúa, J),
	(Lavilla, P),
	(Chateau, J),
	(Malaguzzi, L),
	(Peralta Espinosa, M. V),
	(Red Territorial de Educación Infantil de Cataluña),
	(Papalia, D),
	(Sharp, M),
	(Travers, R),
	(Suárez, M),
	(Ruz, J),
	(Banfi, J. C),
	(B., C. G),
	(Brower, W),
	(Gallardo, J. R),
	(Pedreira, J. L),
	(Collabed, F. M),
	(Pereda, J. J),
	(Testut, L),
	(Labbok, M),
	(Uribe C., P),
	(Rosales, S),
	(De Azevedo, F),
	(Garretón, M. A),
	(Banks, O),
	(Bonal, X),
	(Bourdieu, P y Passeron, J. C),
	(Chinoy, E),
	(Corcuff, P),
	(Durkheim, E),
	(González-Anleo, J),
	(Moreno B., E),
	(Tirado B., D),
	(Wright Mills, C),
	(Baumgart, F),
	(Gombrich, E. H),
	(Akoschky, J),
	(Morales, O),
	(Museo Chileno de Arte Moderno),
	(Becker, J, Reid, K, Steinhaus, P y Wieck, P),
	(Dewey, J),
	(Lavanchy, S y Susuki, E),
	(Peralta, M),
	(Torres, J),
	(Malagón, L, Rodríguez, L y Ñáñez, J),
	(Borrego, C),
	(Bartolomé, A),
	(Arenas, A. C),
	(Boggino, N),
	(Albala, C y Burrows, R),
	(Celedón, J. M),
	(Ruz, M),
	(Périn, J. D),
	(Verdú, M. J),
	(Revista Latinoamericana de Educación Inclusiva),
	(Educación Siglo XXI),
	(Guía de Actuación),
	(Comamalas, J),
	(Wolf, R),
	(Britton, L),
	(Malajovich, A),
	(Porstein, A),
	(Ferreiro, E y Gómez, M),
	(Vivaldi, M),
	(Rodríguez, G),
	(Cuervo, R. J),
	(Fuentes, J. L),
	(Neneca, P y Cabrera, A),
	(Sánchez Pérez, A),
	(Faw, T),
	(Kail, R. V y Cavanaugh, J. C),
	(Papalia, D. E; Olds, S. W; Feldman, R. D),
	(Hoffman, L; Paris, S; Hall, E),
	(Vidal, L. M y Diaz, C. J),
	(Craig, G. J),
	(Condemarín, M y Medina, A),
	(Pitluk, L),
	(Ávalos Órdenes, V y Collao Jofré, D),
	(Román, M),
	(Tobón, S),
	(Mateu, M),
	(Stokoe, P y Schächter, A),
	(Del Moral, A),
	(Comellas, M. J),
	(Armaíz Sánchez, P),
	(Restrepo, H. E),
	(Jiménez, E. O),
	(Callabed, J y Callabet, F. M),
	(Callabet, F. M),
	(Rodríguez, P),
	(Rosales, L. M. S),
	(Teleduc),
	(Borone, L. R),
	(Cerda Díaz, L),
	(Ballester, M y Otros),
	(San Martí, N),
	(Stobart, G),
	(Castilla, S (Coord.)),
	(Monereo, C (Coord.)),
	(Perrenaud, P),
	(Taut, S, Cortés, F, Sebastian, C y Preiss, D),
	(Good, T. L. y Brophy, J),
	(Henson, K),
	(Loughlin, C. E. y otros),
	(Alvares, A),
	(Araújo, J. B. y otros),
	(Ausubel, D),
	(Daud, B. y Grahome, F),
	(Gardner, H),
	(Hagarty, S. y Pocklington, K),
	(Klinger, C),
	(Albert, L. S),
	(Alejandro López, A. P),
	(Novara, D. y Pavani, E),
	(Segal, J),
	(Rulicki, S),
	(Steiner, C. P),
	(Stevens, J. O),
	(Abarca Melo, N),
	(Hemsy, V),
	(Sánchez Ortega, P),
	(Talero-Gutiérrez, C., Zarruk-Serrano, J. G. y Espinosa-Bode, A),
	(Shapiro, L. E),
	(Cañal, S. F. y Cañal, R. C),
	(Consejo Nacional de la Cultura y las Artes),
	(García-Huidobro, H),
	(Gubern, R),
	(Potes, R. L),
	(Del Canto, Fariña L., García-Huidobro Valdés M., Sedano Solís Ana, y Compañía La Balanza),
	(García-Huidobro Valdés M., y Compañía La Balanza),
	(Cembranos Pérez, C., Gallego Pérez, P., y Cárdenas Bernat, M),
	(Corres Fontecilla, Pedro Pablo),
	(Hasche Sánchez, Renato),
	(Hernández Baqueiro, Alberto y Constante López, Alberto),
	(Subsecretaría de Educación Parvularia),
	(Briones, Guillermo),
	(Casanova, María Antonia),
	(Castillo Arredondo, Santiago),
	(Cerda Gutiérrez, Hugo),
	(Lukas Mujika, José Francisco),
	(Monedero Moya, Juan),
	(Pitluk, Laura),
	(Santos Guerra, Miguel Ángel),
	(Stobart, Gordon),
	(Bohm, W., y Schiefelbein, E),
	(Contreras Domingo, J),
	(Peralta, María Victoria),
	(Peralta Espinosa, M),
	(Picazo Verdejo, P),
	(Cerda, L),
	(Silva Torrealba, B),
	(Stainback, S., y Stainback, W),
	(Jiménez, C),
	(Harf, R., Origlio, F., Pitluk, L),
	(Stokoe, P., Schächter, A),
	(Laura, P., Dente, L., Gonzalez, A),
	(López, A),
	(Novara, D),
	(Feldman, J),
	(Ruiz, A),
	(Steiner, C),
	(Stevens, J),
	(Bonals, J),
	(Asti Vera, A),
	(Wartofsky, M),
	(Hernández Sampieri, R., Fernández Collado, C., Baptista Lucio, P),
	(Valles, M),
	(León, O., Montero, I),
	(Rodríguez, G., Gil, J., García, E),
	(Labinowicz, E),
	(Monfort, M),
	(Olerón, P),
	(Papalia, D., Wendkos, S),
	(Rondal, J),
	(Unidad de Educación Especial, Ministerio de Educación),
	(Covey, S. R),
	(Cordeviola de Ortega, M. I),
	(Goleman, D., Hernández Chambers, D),
	(Fernández R., I),
	(Jauli Dávila, I., Reig Pintado, E., Soto Pineda, E),
	(Morales Frías, J),
	(Schargel, F. P),
	(Torti, A),
	(Carrasco, A),
	(Murillo, J),
	(Hill, C., Jones, G),
	(Cañal Santos, F., Cañal Ruiz, C),
	(Del Canto Fariña, L., García-Huidobro Valdés, M., Sedano Solís, A),
	(Díaz, J., Genovese, C),
	(García-Huidobro Valdés, M., Compañía La Balanza),
	(Mc Callion, M),
	(González del Valle, C),
	(Céspedes Calderón, A),
	(Fay, D.),
	(Gallego Ortega, J., Fernández de Haro, E),
	(Hoyuelos Planillo, A., Riera Jaume, M. A),
	(Malajovich, A., Ponce, R.),
	(Martínez Mendoza, F),
	(Requena, M. D., Sáinz de Vicuña, P. P),
	(Soler Fiérrez, E),
	(Sugrañes, E., Alós, M., Andrés, N.),
	(Zabalza Beraza, M. A),
	(López, A. P),
	(Novara, D., Pellai, A),
	(Feldman, J. R),
	(Gombrich, E),
	(Aldámiz-Echevarría, M., Alsinet, J., Bassedas, E),
	(Ramírez Camacho, R),
	(Claxton, G),
	(Díaz, B. F., Hernández, R. G),
	(Perales, F. J),
	(Céspedes, A),
	(Marín, V),
	(Rolandi, A),
	(UNICEF),
	(Morin, E),
	(García, A., Llul, A),
	(Mühlhauser, V. R. G),
	(Peralta, V),
	(Sarlé, P., Rosemberg, C),
	(Acuña, M. F),
	(Bravo, J. A),
	(Chamorro, M. D),
	(Peterson, P. S.-L),
	(Rey, M. E),
	(Peralta, M. V),
	(Hoyuelos, A., Riera, A),
	(Lacoboni, M),
	(Lecannelier, F),
	(Mendoza, F. M),
	(Zavalloni, G),
	(Peralta, E),
	(Novara, D., Pagella, E),
	(Rulicki, S., Caamaño, M),
	(Belenes, L. (eds)),
	(Du Ry van Beest, G),
	(Frías Valenzuela, F),
	(Krebs, R),
	(López Melero, R. (eds)),
	(Pijoan, J),
	(Pinto, J., Salazar, G),
	(Silva Galdames, O),
	(Villalobos, S., Silva, O),
	(Villalobos, S),
	(Hernández Cardona, X),
	(Rueda, D),
	(Esquivel Fernández, A., González, E),
	(Casanova, M. A),
	(Gagné, R),
	(Muhlhauser, V. R. Grethel),
	(Becker, K. R. Joni),
	(Kaufman, R),
	(Reyzabal Rodríguez, A. S. María),
	(Montessori, M),
	(Moor, P),
	(Orbe, F. B),
	(Pugmire, M. C),
	(Bravo, E. F. Rafael),
	(Gagné, R. L. B. Robert),
	(Antúnes, F. I. Serafín),
	(Lavanchy, E. S. Silvia),
	(Castillo, Cristina),
	(Hendrix, Charles),
	(Gallego Ortega, José Luis),
	(Araya, Roberto),
	(Malajovich, Ana),
	(Martinez Mendoza, Franklin),
	(Coll, César),
	(Furth, H. G., Wachs, H),
	(Subsecretaría Educación Parvularia),
	(Aguilar, Esperanza),
	(Bal, Mieke),
	(Campbell, Joseph),
	(Cañelles, Isabel),
	(Egri, Lajos),
	(Field, Syd),
	(Gubern, Roman),
	(Mckee, Robert),
	(Seger, Linda),
	(Stanislavski, Constantin),
	(Vogler, Christopher),
	(Bernabeu, N. & Goldstein, A),
	(Tonucci, F),
	(Acaso, M),
	(Ferreiro, E. & Gómez, M),
	(Solé, I),
	(Villalón, M),
	(Bettelheim, B),
	(Bru, Bernadette & Charles),
	(Carracedo, Sandra),
	(Dotras, Leticia),
	(Francia, Alfonso),
	(Flores, Hilerio, Dalina),
	(Gómez Palacios, José Joaquín),
	(Gómez de Lora, Chema),
	(Jesualdo),
	(Busquets, Jordi),
	(Pastoriza, Dora),
	(Peña, Muñoz, Manuel),
	(Cervera, M. & Feliú, H),
	(Ministerio de Educación, Ciencia y Tecnología de la República Argentina),
	(Zabalza, M. A),
	(Junta Nacional de Jardines Infantiles),
	(Caballenas, I., et al.),
	(Cerda, L.),
	(Decroly, O. & Monchamp, E),
	(Lantieri, L.),
	(Peralta, E.),
	(Peralta, M.),
	(Pitluk, L.),
	(Álvarez, A.),
	(Bravo, L.),
	(Monfort, M.),
	(Olerón, P.),
	(Papalia, D. & Wendkos, S.),
	(Aliaga, V.),
	(Araya, D.),
	(Aliaga, V. & Araya, D.),
	(García Huidobro, B. & Gutiérrez, B.),
	(García-Huidobro, J. & Falabella, A.),
	(Lira, M. & Edwards, G.),
	(Santelices, L. & Scagliotti, J.),
	(Sapelli, C.),
	(Fernández, A. M. & López, M.),
	(Goetz, J. P. & Lecompte, M.),
	(Guilford, J. P. & Fruchter, B.),
	(Kemmis, S. & McTaggart, R.),
	(Rodríguez, G., Gil, J. & García, E.),
	(Bajtín, M. M.),
	(Brown, Edward J.),
	(Dostoievski, F. M.),
	(Figes, Orlando),
	(Hickey, Martha Weitzel),
	(Nabokov, Vladimir),
	(Said, E. W.),
	(Santiván, F.),
	(Service, R.),
	(Schostakovsky, P.),
	(Tolstói, L.),
	(Steiner, G.),
	(Comella, A.),
	(Wolf, R.),
	(Alvarez, A.),
	(Arends, R.),
	(Armani, M. B.),
	(Daniels, H.),
	(Malajovich, A.),
	(Ortega, J. I. G.),
	(Pestalozzi, J. H.),
	(Zabalza, M. Á.),
	(Bisquerra, R. et al.),
	(Lecannelier Acevedo, F.),
	(Fournier, M. C.),
	(Reyzábal, M. V. & Casanova, M. A.),
	(Britton, J. R., & Bello, L.),
	(Caccuri, V.),
	(González, E.),
	(Stephen R. Chapman y Larrk),
	(Jiménez C, Gómez M),
	(Robles, J.),
	(Linaza, L. M. A.),
	(Asensio-Cuesta, S., Ceca, M. J. B., & Más, J. A. D.),
	(Adler, R. B., Elmhhorst, J. M., Mascaró, S. P., & González, P. J. R.),
	(Portellano, J.),
	(Netter, F.),
	(Braunstein, N.),
	(Leahey, Thomas H.),
	(Le Senne, R.),
	(Ulich, D.),
	(García-Borrón, J.C.),
	(Whittaker, J.),
	(Cruz, Isabel de la.),
	(Mauss, Marcel),
	(Horton, Paul, Moya, Rafael),
	(Kottak, Conrad Phillip),
	(Wallner, Ernest M.),
	(Freud, S.),
	(Alejandro López, A. P.),
	(D. Novara, E. P.),
	(Feldman, J. R.),
	(Ruiz, A.),
	(Sergio Rulicki, M. C.),
	(Maturana Romesín, Humberto),
	(Berlo, David),
	(Fuentes de la Corte, Juan Luis),
	(Luhmann, Niklas),
	(Bravo M., Francisco),
	(Otero Bello, Edison),
	(Baylon, Christian),
	(Fuscoe, Kate, Garside, Barbara, Prodromou, Luke),
	(Soars, Liz, Soars, John, Wheeldon, Sylvia),
	(Heyer, Sandra),
	(Lebeau, Ian, Rees, Gareth),
	(Norris, Maggie, Siegfried, Donna Rae),
	(Baró, I. M.),
	(Barón, R., Byrne, D.),
	(Barra, E.),
	(Crespo, E.),
	(Fischer, G.),
	(Fichter, J.),
	(Montero, M.),
	(Moscovici, S.),
	(Moya, J.),
	(Pérez Soto, C.),
	(Kleinke, C.),
	(Leahey, T.),
	(Domjan, Michael.),
	(Gil Piédrola, Sierra López),
	(Martínez-González, M. A.),
	(Hernández-Aguado, I., Gil de Miguel, A., Lumbreras Lacarra, B.),
	(Albala, C., Olivares, S., Salinas, J., Vio, F.),
	(O'Sullivan, S.),
	(Townsend, C.),
	(Craig, C.),
	(Alfaro, J., Berroeta, H.),
	(Musitu, G., Herrero, J., Cantera, L., Montenegro, M.),
	(Faw, T.),
	(Kail, R. V., Cavanaugh, J. C.),
	(Hoffman, L., Paris, S., Hall, E.),
	(Vidal, L., Diaz, C.),
	(Craig, Grace J.),
	(Papalia, Diane E.; Olds, Wendkos Sally; Feldman, Duskin Ruth),
	(Almonte, C.; Montt, M.; Correa, A.),
	(Hoffman, Lois; Paris, Scott; Hall, Elizabeth),
	(Watzlawick, Paul; Beavin, Janet; Jackson, D.),
	(Berger, Milton),
	(Suzzane Midori Anna; Josep Brown),
	(Ritvo, E.; Glick, I.),
	(Freud, Sigmund),
	(Fenichel, Otto),
	(Bower, Gordon H.;Hilgard, Ernest R.),
	(Mayor, Richard E.),
	(Domjan, Michael),
	(Thomas H.),
	(Piaget, Jean),
	(Whittaker),
	(Segal, H.),
	(Kernberg, O. F.),
	(Riquelme, R.; Oksenberg, A.),
	(Cloninger, S.),
	(Papalia, Diane E.; Wendkos Sally; Feldman, Duskin Ruth),
	(Ascensión Belart, M. F.),
	(Bowen, M.),
	(Haley, J.),
	(Sarquis, C.),
	(Papalia, Diane E.; Wendkos Sally),
	(Berman, Morris),
	(Cloninger, Susan C.),
	(Jiménez V., Carlos Alberto),
	(Jourard, S.M.; Landsman, T.),
	(Hardy Leahey, T.),
	(Naranjo, Claudio),
	(Perls, Frederick),
	(Rogers, Carl R.),
	(Wilber, Ken),
	(Casassus, Juan),
	(Csikszentmihaly, Mihaly),
	(Rodríguez, D.),
	(Pereda, S.; Berrocal, F.),
	(López-Mejías, F.),
	(De La Plaza, Javiera),
	(Campbell, Susan),
	(Alcover, C.; Martínez, D.; Rodríguez, F.; Domínguez, R.),
	(Americana, d. P.),
	(Arnedo, Bembibre, & Triviño),
	(Ballesteros, F.),
	(Belloch, A.; Sandín, B.; Ramos, F.),
	(Caponni, R.),
	(Cormier, H.; Sheilyn, L.),
	(Gil, R.),
	(González, B.),
	(J.Portellano),
	(Juan Dittborn, S. R.),
	(Leveton, E.),
	(Levisky, D.),
	(OMS, O. M.),
	(Parmelee, D.; David, R.),
	(Salud, O. P.),
	(Scandar, R.),
	(Coll, C.; Palacios, J.; Marchesi, A.),
	(Grande, B.; Pemoff, J.),
	(Santos, Miguel Ángel),
	(Arancibia, V.; Herrera, P.; Strasser, K.),
	(Siquier de Ocampo, M.; García, M.; Grassano, E.),
	(Alicia Passalacqua, A. C.),
	(Bohm, E.),
	(Ceberio, M.),
	(Gravenhorst, M.),
	(Hammer, E.),
	(Kacero, E.),
	(Ocampo, M. S.; Arceno, M. G.; Pícolo, E. G.),
	(Rorschach, H.),
	(Silvia Querol, M. C.),
	(Silvia Querol, S. A.),
	(Warren, J. N.),
	(Weigle, C.),
	(Bellack, L.),
	(Bender, L.),
	(Cattaneo, B.),
	(Cattell),
	(Doll, E.),
	(E.M García Pérez, A. M.),
	(Golden, C.),
	(J.N. Butcher, J. G.-P.),
	(Klopfer, B.),
	(Lobos, A.),
	(Margarita Haeussler, T. M.),
	(Murray, H.),
	(Paulina Kernberg, A. W.),
	(Phillipson, H.),
	(Rey, A.),
	(Rivera, O.),
	(Roselli, E. M.),
	(Soledad Rodríguez, V. A.),
	(Valeria Ramírez, R. R.),
	(Verthelyi, R. F.),
	(Weschler),
	(Condemarín, Chadwick, Milicic),
	(Soto, A.; Strasser, S.),
	(Corsi, J.),
	(Fernández, A.; Rodríguez, B.),
	(Garrido, V.),
	(Rodríguez, G.; Gil, J.; García, E.),
	(Perez Serrano, Gloria),
	(Kerlinger, F.),
	(Sierra Bravo, R.),
	(Campbell, D.; Stanley, J.),
	(León, O. E.; Montero, I.),
	(Fernández, A. M.; López, M.),
	(Davidoff, L.),
	(Hardy Leahey, T.; Jackson Harris, R.),
	(Kandel, E.; Schwartz, J.),
	(Revé, J. M.),
	(Varela, F.),
	(Whishaw, Kolb),
	(Diamond, M.; Scheibel, A.; Elson, L.),
	(Gonzalez, B.),
	(Kolb, & Whishaw),
	(Lavados, & J. A. S.),
	(Rosselli, E. M.),
	(Albert, L. S.),
	(Steiner, C. P.),
	(López, A. P.),
	(D.),
	(Rulicki, S. M. C.),
	(Cooligan, H.),
	(Hernández, R.; Fernández, C.; Baptista, P.),
	(Guilford, J. P.; Fruchter, B.),
	(Watzlawick, P.; Beavin, J.; Jackson, D.),
	(Kenney, B.),
	(Serebrinsky, H.),
	(Ibáñez, J.),
	(Rodríguez, V. A.),
	(Ramírez, R. R.),
	(Salazar, M.),
	(Barón, R.; Byrne, D.),
	(Cooper, D.),
	(Moulian, T.),
	(Nunnally, J. C.),
	(Taylor, S. J.; Bogdan, R.),
	(López - Mejías, F.),
	(Ander-Egg, E.; Aguilar Idañez, M.J.),
	(Cerda Gutierrez, H.),
	(Pereña Brand, J.),
	(Pérez Serrano, G.),
	(Tejada Fernández, J.),
	(Martínez, A.),
	(Bauman, Z.),
	(Colegio de Psicólogos de Chile),
	(Reyzábal, M. V.; Casanova, M. A.),
	(Britton, J. R.; Bello, L.),
	(Swokowski, E. W.; Trigueros, M.),
	(Miller, C. D.; Heeren, V. E.; Hornsby, E. J.),
	(Hawley, D.; Hawley, R.),
	(Caccuri, Virginia),
	(Frye, C.; Scott, P. P.),
	(Horngren, Charles T.; Harrison Jr., Walter; Oliver, M. Suzanne),
	(Bosch Bousquet, Julio; Vargas Valdivia, Luis),
	(Salort S., Vicente),
	(Fajardo Castro, José),
	(Torres Cárdenas, Fernando),
	(Koontz, H.; Weihrich, H.),
	(Chiavenato, I.; Mascaro, S. P.; Mares, C. J.),
	(Jones, G. R.; George, J. M.),
	(Robbins, S. P.; Coulter, M.),
	(Bateman, T. S.; Snell, S. A.; Sanchez, S. G. A.; Nava, L. L. C.; Paterna, P. M.; Lavigne, M. A.; Mares, C. J.),
	(Abarca, N.),
	(Constante López),
	(Frederick, Robert E.; Carril Villareal, M.; González Martínez, J. L.),
	(Mosley, D. C.; Megginson, L. C.; Pietri, P. H.),
	(Núñez, O. R.),
	(Podcast Audio),
	(McCarthy, M.; McCarten, J.; Sandiford, H.),
	(Wilson, K.; Healy, T.),
	(Varas C., Humberto),
	(Chiavenato, I.; Sapiro, A.; Mascaro, S. P.),
	(Chiavenato, I.; Guzmán, B. M. P.; Mascaró, S. P.),
	(Brigham, E.; Houston, J.),
	(Besley, S.; Brigham, E.),
	(Pacheco Cañete, Matilde),
	(Instituto Mexicano de Contadores Públicos),
	(Holmes, Arthur W.; Overmyer, Wayne S.),
	(Cepeda Alonso, Gustavo),
	(Ocampo, S. J. E.),
	(Ñaupas, P. H.; Yaldivia, D. M. R.; Palacios, Y. J. J.; Romero, D. H. E.),
	(Hernández, S. R.; Fernández, C. C. B. L. M. P.),
	(Adler, R. B.; Elrnhorst, J. M.; Mascaró, S. P.; González, P. J. R.),
	(Britton, J. R.; Bello, I.),
	(Mott, Robert L.; trad. Córdova Just, Arturo),
	(Ferrer Giménez, Carlos; Amigó Borras, Vicente),
	(Timings, R. L.; trad. Naves Ruiz, Juan),
	(Apilluelo, A.; Manuel, J.; Ibañez Carabantes, P.; Ubieto Artur, Pedro),
	(Cobos Gutiérrez, C.; Cidoncha, R.),
	(Dubbel, H.),
	(184.2),
	(Cirovic, M. M.),
	(Boylestad, R. L.; Nashelsky, L.),
	(Pérez, E. M.; Acevedo, J. M.; Silva, C. F.),
	(Galabru, P.),
	(Solé, A. C.),
	(Salvador, A. G.),
	(Houldcroft, P. T.),
	(Molera Solà, Pere),
	(Giachino, Joseph William),
	(Appold, Hans),
	(Asociación Española de Ensayos No Destructivos),
	(Castillo González, Denis Román; Escalona Rodríguez, Ernesto Antonio),
	(Gallegos Tiska, Patricio Esteban; Ordenes Avalos, Jorge Geovanni),
	(Ñaupas, P. H.; Valdivia, D. M. R.; Palacios, V. J. J.; Romero, D. H. E.),
	(Hernández, S. R.; Fernández, C. C.),
	(Barberá, E.),
	(Adler, R. B.; Elmhorst, J. M.; Mascaró, S. P.; González, P. J. R.),
	(López, J. C.; López, J. E.; García, B. P.),
	(Security Dresser),
	(Hurlbut, C. S.; Dana, J. D.),
	(Galán, H. E.; Regueiro, G.-B. M.),
	(López, J. C.),
	(Heinrich, E. Wm.),
	(Mackenzie, W. S.),
	(Yañez, E.),
	(Latorre, J.),
	(Codelco Chile),
	(Pavéz, O.),
	(Astorga Flores, A.),
	(Universidad del Norte),
	(Fernández, B. P.),
	(González, M. R.),
	(Castejón, O. A.; Santamaría, G.),
	(Suban, P.; Schmitt, M. L.; Nagores, C. G.),
	(Creus, S. A.),
	(Huidobro, V.),
	(Chanes, M.),
	(Rojo, D.),
	(Godoy, C.),
	(Anderson, J.),
	(Davis, R.; Foote, F.),
	(Valdés, D. F.),
	(Taton, R.),
	(Wirshing, J. R.),
	(McCormac, J. C.),
	(Fernández, L.; Universidad de León),
	(Llamas, Z.),
	(Tugendhat, E.; Vicuña, A. M.; López, C.),
	(Naupas, P. H.; Valdivia, D. M. R.; Palacios, V. J. J.; Romero, D. H. E.),
	(Hernández, S. R.; Fernández, C. C. B.),
	(Vallejo-Nágera, J.),
	(Maturana, H.),
	(Ontoria, A.; et al.),
	(Pimienta, J.),
	(Serafín, M.),
	(Fernández García, T.),
	(Zamanillo, T.),
	(Ander Egg, E.),
	(Salazar, G.),
	(Garcés, M.),
	(López Araguren, E.),
	(Costas, X.),
	(Quezada, M.),
	(Ahumada, J.),
	(Barro, R.; Febrero, R.; Grilli, V.),
	(Cademártori, J.),
	(Ministerio Secretaria General de Gobierno. Secretaría de Comunicaciones y Cultura),
	(Perret, B.; Roustong, G.),
	(Arent, H.),
	(Molina Molina, L.; Romero Saint Bonet, C.),
	(Swan, M.),
	(Eastwood, J.),
	(Ritzer, G.),
	(Giner, S.),
	(Costa, X.),
	(Kottac, C.),
	(Berdichewsky, B.),
	(Eroles, C.; Gagneten, M.; Sala, A.),
	(Anguera, M. T.),
	(Hamme, M.; Atkinson, P.),
	(Vallés, M. S.),
	(Tenorio, F.),
	(Ferreira, M.; Corvalán, E.),
	(Devés Valdés, E.),
	(Úcar, X.; Llena, A.),
	(Esposito, R.),
	(Heras i Trias, P.),
	(Tönnies, F.),
	(Touraine, A.),
	(Threvitick, P.),
	(Holfstand, C.; Gómez, J.),
	(Peñafiel, E.; Serrano, C.),
	(Juarez, M.),
	(Babbie, E.),
	(Reza, F.),
	(Fitoussi, J.; Rosanvallon, P.),
	(Castel, R.),
	(Luhmann, N.),
	(Fernández García, T.; López Peláez, A.),
	(Kisnerman, N.),
	(Zastrow, Ch.),
	(Giomi, C.; Ulla, L.; García, P.),
	(Giomi, C.; Ulla, L.),
	(Ajenjo, A.),
	(Mendicoa, G.),
	(Instituto Latinoamericano de Planificación Económica y Social),
	(Gutiérrez, J.),
	(Tschorne, P.),
	(Zastrow, Ch. H.),
	(Sandoval, A.),
	(Pérez, G.),
	(Ruiz, J.),
	(S. Henry J. East; C. Schummiz (Coords.)),
	(Schultz, F.),
	(Shaffer, D.),
	(Felman, R.),
	(Kuri, M.),
	(Baddeley, A.),
	(Goldstein, B.),
	(Alywin de Barros, N.; Solar, O.),
	(Barg, L.),
	(Segalen, M.),
	(De Robertis, C.),
	(Tonon, G.),
	(Escartín, M. J.; Suárez, E.),
	(Canales, M. (Coord.)),
	(Delgado, J.; Gutiérrez, J. (Coord.)),
	(García, M.; Ibáñez, J.; Alvira, F. (Comp.)),
	(Gordo, A.; Serrano, A.),
	(Banks, S.),
	(Aguayo, C.),
	(Kisnerman, N. (Comp.)),
	(Rozas, M.),
	(Rojas Soriano, R.),
	(Pastén Cordobés, F.),
	(East, S. H. J.; Schummiz, C. (Coords.)),
	(Grau, O. et al.),
	(Olavarría, J. et al.),
	(Beckhard, R.),
	(Guizar, R.),
	(De Tommaso, A.),
	(Verderber, R.),
	(Loprete, C.),
	(Vargas Sierra, C.),
	(Oliver González, A.),
	(Hughes, J.; Stephenson, H.; Dummet, P.),
	(Clarke, S.),
	(Tilbury, A. et al.),
	(Pasua Febles, I.),
	(Fernández Estañ, M.),
	(León Rodríguez Román, M.),
	(Schrampfer, B.; Hagen, S.),
	(Pöchhacker, F.),
	(Aznar, J.),
	(Cuervo, R.),
	(De Saussure, F.),
	(Jakobson, R.),
	(Knapp, M.),
	(Lázaro, F.),
	(Real Academia Esp.),
	(Ullmann, S.),
	(Coseriu, E.),
	(García Yebra, V.),
	(Hurtado, A.),
	(Orellana, M.),
	(Owens, R.),
	(Samuelsson-Brown, G.),
	(Ferreiro, E.; Gómez, M.),
	(Calvo Rodríguez, A.),
	(Alcoba, S. (Coord.)),
	(Gómez Torrego, L.),
	(Reyzábal, M.),
	(Sánchez Lobato, J. (coord.)),
	(Centro de Investigación y Publicaciones del Idioma),
	(Busquets, L.; Bonzi, L.),
	(Savage, A.; Shafiei, M.),
	(Carreres, Á.; Noriega-Sánchez, M.; Calduch, C.),
	(Jiménez, J. A. F.; Muñoz-Basols, J.),
	(Orozco Jutorán, M.),
	(Nolan, J.),
	(Bartoll, E.),
	(Cronin, M.),
	(Duro, M.),
	(Díaz, J.),
	(Hortal Alonso, A.),
	(Gouadec, D.),
	(Álvarez, G.; Díaz, N.),
	(Bühler, K.),
	(Pilleux, M.),
	(Kristeva, J.),
	(Painean, O.),
	(Berman, A.; Bonilla Artiga),
	(Calvi, M. V.),
	(Newmark, P.),
	(Vázquez-Ayora, G.),
	(Gillies, A.),
	(Fournier, C.),
	(Martín, V. G.),
	(Rodríguez, J. V.),
	(Lorenzini, M. E.; Ruiz, J. M.),
	(Ciruelo, P.),
	(Sánchez Pérez, A.),
	(Davis, J.; Liss, R.),
	(Cordon, J. A.; Pinto, M.),
	(Gonzalo García, C.; García Yebra, V.),
	(Translation Centre for the Bodies of the European Union),
	(United Nations),
	(Garrido Medina, J.),
	(Kaufman, A.; Rodríguez, M.),
	(Mignolo, W.),
	(Pelayo, N.; Cabrera, A.),
	(Gamero, S.),
	(Pavel, S.; Nolet, D.),
	(Alarcón Palma, M.; Sánchez Medina, M.; Pecchi Sánchez, A.),
	(Harmer, J.; Rossner, R.),
	(James, C.),
	(Lado, R.),
	(Lewis, M.),
	(Richards, J.; Platt, J.; Platt, H.),
	(Muñoz, C.),
	(Neunzig, W.; Milheiro Tanqueiro, H.),
	(Rojo, A.),
	(Saldana, G.; O'Brien, S.),
	(Williams, J.; Chesterman, A.),
	(Doff, A.; Goldstein, B.),
	(O'Dell, F.; et al.),
	(Byrne, J.),
	(Ewer, J. R.; Latorre, G.),
	(García, Y. V.; Gonzalo, G. C.),
	(Herbert, A. J.),
	(Maillot, J.),
	(Martínez López, A.),
	(Olohan, M.),
	(Orozco, M.),
	(Sales, S. D.),
	(Pizarro, A.),
	(Gile, D.),
	(Alcaraz Varó, E.; Hughes, B.),
	(Campbell, S.),
	(Collazo, J. L.),
	(Gámez, T. D.),
	(Grosman, M.; Kadric, M.; Kovačić, I.; Snell Hornby, M.),
	(Hervey, S.; Higgins, I.; Hayward, L. M.),
	(Merino, J.; Sheerin, P. H.),
	(Non-Mother Tongues in Professional Practice and Training),
	(Torrego, L. G.),
	(Gamero Pérez, S.),
	(Chiavenato, I.; Mascaró, S. P.; In Mares, C. J.),
	(Lavigne, M. A.; In Mares, C. J.),
	(Horngren, C. T.; Harrison, W.; Oliver, M. S.),
	(Bosch Bousquet, J.; Vargas Valdivia, L.),
	(Parkin, M.; Esquivel, G.; Avalos, M.),
	(Beker, V.; Mochón, F.),
	(Massad, C.; Pattillo, G.),
	(Maximiano, A. C. A.; Chávez, S. J. L.),
	(Chiavenato, I.; Sapiro, A.; Mascaró, S. P.),
	(Torres, Gabriel),
	(González M., Carlos A.),
	(Novak, J. D.; González, C.),
	(Sambrano, J.; Steiner, A.),
	(Fernández, S. E.),
	(Koontz, H.; Weihrich, H.; Sánchez, S. G. A.; Gómez, M. J.),
	(Cohen, K. D.; Asín, L. E.),
	(Kelley, T.; Littman, J.),
	(Alles, M. A.),
	(Arias, G. F.; Heredia, E. V.),
	(Byars, L. L.; Rue, L. W.),
	(Dressler, G.),
	(Kotler, P.; Armstrong, G.; Cámara, I. D.),
	(Costa, M.; López, M. E.),
	(Vallés, A.),
	(Jiménez, J.; Velilla, N.),
	(Klein, C.),
	(García, M. C.),
	(Tarbuck, E. J.; Lutgens, F. K.),
	(Barettino, D.; Wimbledon, W. A. P.; Gallego, E.),
	(Mourgues, F. A.; Schilling, M.; Castro, C.),
	(Dana, J. D.; Hurlbut, C.),
	(Klein, C.; Hurlbut, C. S.),
	(Bannister, A.; Raymond, S.; Baker, R.; de la Cera Alonso, J.; López, R. O.),
	(Domínguez García Tejero, F.; Thompson, M. M.; Lillcsand, T. M.; Kiefer, R. W.; Venegas, M.; Veruette, F.; Schmoock Pivaral, W. J.),
	(Gutiérrez, C. P.; Nieto, A. L. M.),
	(Wolf, P. R. B.; Wolf, R. C. P. R.; Brinker, R. C.; Pasini, C. V.; Domínguez García-Tejero, F.; Romeo, C. T. R.),
	(Sillano, M. I.; Pérez Rojas, J.),
	(Buzai, G. D.; Baxendale, C. A.),
	(Gómez Delgado, M.; Cano, B.; Ignaciocoaut, J.),
	(Romero, T. D.; Martínez, E. P.),
	(Perkins, D.; Ienke, K. R.; Kevin, R. H.),
	(Kraus, H.; Hunt, E. F.; Ramsdell, W. S.; Alvargonzález, L. N.),
	(Ballou, R. H.; de Lemus, P. R.),
	(Silvia Maturana; Helvio Soto Salles),
	(Bustillo Revuelta, M.; López Jimeno, C.),
	(Millan, A.),
	(Rojas Caballero, D.; Paredes, J.),
	(Sillitoe, R.),
	(Tarbuck, E.; Lutgens, F.),
	(Tosdal, R.; Richards, J.),
	(Mac-Lean, A.),
	(Castro, A.),
	(Niemeyer, R.),
	(Ayala-Carcedo, R.; Oleína Cantos, J.),
	(Keller, E. A.),
	(Anguita Virella, R.; Moreno Serrano, F.),
	(Ayala, F.; Ordá, J. F. (coord.)),
	(Fernández, S. R.; Fernández, C. C. B. L. M. P.),
	(Mott, R. L.; Córdova Just, A. (trad.)),
	(Ferrer Giménez, C.; Amigó Borras, V.),
	(Timings, R. L.; Naves Ruiz, J. (trad.)),
	(Apilluelo, A.; Manuel, J.; Ibañez Carabantes, P.; Ubieto Artur, P. E. D. R. O.),
	(Mott, R. L.; Córdova Just, A.),
	(Houldcroft, P. T. (Peter Thomas)),
	(Molera Solà, P.),
	(Giachino, J. W.),
	(Appold, H.),
	(Castillo González, D. R.; Escalona Rodríguez, E. A.),
	(Gallegos Tiska, P. E.; Ordenes Avalos, J. G.),
	(Codelco Chile. División El Teniente),
	(Astorga Flores, Ángel),
	(Cáceres Arenas, Germán),
	(Hidrometalurgia del Cobre),
	(Castejn, O. A.; Santamaría, G.),
	(Fernández, L.; Universidad de León.),
	(Tugendhat, E.; Vicuña, A. M.; Lopez, C.),
	(Hernández, S. R.; Fernández, C. C. B. L. M. P. Q.),
	(Chapman, S. R.; Larrk.),
	(Jiménez, C.; Gómez, M.),
	(Asensio-Cuesta, S.; Ceca, M. J. B.; Más, J. A. D.),
	(Ñaupas, P. H.; Valdivia, D. M. R.; Palacios, Y. J. J.; Romero, D. H. E.);