INSERT INTO Editorial (name) VALUES
	('México: Thomson.'),
	('Madrid: La Muralla'),
	('Madrid; Escuela Española'),
	('México: lnternational Thomson'),
	('0'),
	('México: Grupo Edit. lberoamérica'),
	('México: Pearson.'),
	('Madrid: Anaya Multimedia'),
	('México: Alfaomega'),
	('Argentina: Grami'),
	('Madrid'),
	('Madrid: McGraw-Hill, lnteramericana de España'),
	('México: McGraw-Hill'),
	('México: McGraw-Hill lnteramericana Editores'),
	('Distrito Federal: McGraw-Hill Interamericana.'),
	('México: Pearson'),
	('México: McGraw-Hill/lnteramericana Editores'),
	('Bogotá: McGraw-Hill'),
	('Santiago, Chile: Coopecultura'),
	('México: PEARSON'),
	('México: Cengage Learning'),
	('Chile: McGraw-Hill'),
	('México: Pearson Educación.'),
	('Harvard Business Review.'),
	('LID'),
	('Cambridge, United Kingdom: Cambridge University Press'),
	('Cambridge University Press'),
	('Cambridge University Press.'),
	('Oxford University Press'),
	('México: McGraw-Hill Interamericana Editores'),
	('Distrito Federal: McGraw-Hill lnteramericana'),
	('México: McGraw-Hill/lnteramericana Editores.'),
	('México: McGraw'),
	('Bogot: McGraw-Hill.'),
	('México: Continental'),
	('Chile: Cono Sur'),
	('Santiago, Chile, Publiley,'),
	('Rosario: Horno Sapiens'),
	('Madrid: Editorial Alianza'),
	('México, D.F: Alfaomega'),
	('México: A lfaornega'),
	('Madrid: Paraninfo.'),
	('Bogotá, D.C. Colombia: Pearson Educación'),
	('Barcelona: Paidós'),
	('Universidad de Chile'),
	('Madrid: McGraw-Hill'),
	('Buenos Aires: Granica'),
	('México, D.F: Trillas'),
	('Madrid: lrwin.'),
	('Colombia: Ed. McGraw Hill.'),
	('México, McGraw Hill.'),
	('México: Ed. Prentice.'),
	('Chile: PEARSON.'),
	('Chile: McGraw-Hill I nterarnericana.'),
	('México: McGraw-1-lill.'),
	('Ciudad de México: Pearson Educación'),
	('Madrid: Pirámide'),
	('México: Prentice-Hall'),
	('Naucalpan de Juárez: Pearson Educación'),
	('Barcelona: UOC.'),
	('Madrid: Narcea Edición.'),
	('Madrid: Síntesis.'),
	('México: Thomso.'),
	('Madrid: La Muralla.'),
	('México: International Thomson'),
	('México: Grupo Edit. lberoamérica.'),
	('México: Alfaomega.'),
	('Madrid: Anaya Multimedia.'),
	('Argentina: Grami.'),
	('Madrid.'),
	('Madrid: McGraw-Hill, Interamericana de España.'),
	('Urrno, SA de Ediciones'),
	('Universitario'),
	('IGME'),
	('In XIII Congreso Geol. Chileno, Antofagasta'),
	('Madrid, España: Thomson Paraninfo.'),
	('Santiago de Chile: Legal Publishing.'),
	('Ediciones Paraninfo'),
	('Espasa-Calpe Argentina'),
	('Reverté,'),
	('Alfaomega'),
	('American Society of Photogrammetry'),
	('Carlos Perez'),
	('Mundi-Prensa'),
	('México, MX: Limusa: Wiley.'),
	('Mundi-Prensa.'),
	('Universidad de los Andes Facultad de Ingeniería. Departamento de Vías. Venezuela.'),
	('Mérida. Venezuela.'),
	('Lugar'),
	('EU DEBA Buenos Aires'),
	('Reverté.'),
	('Díaz de Santos.'),
	('Ed. Gráficas Arias Montana. Madrid.'),
	('Buenos Aires'),
	('Ed Universitaria S.A. Santiago de Chile.'),
	('Lima: EDUNI.'),
	('Mineralium Deposita'),
	('Madrid: Prentice Hall.'),
	('Society of Economic Geologists'),
	('Ariel Ciencia'),
	('Prentice Hall'),
	('Cuadernos de la CEPAL Nº 91'),
	('Serie Geología Ambiental. Madrid.'),
	('Ed. Rueda. Alcorcón'),
	('ITGE. Madrid'),
	('Ed. Balkema. Rotterdam'),
	('Barcelona: Gedisa Editorial'),
	('Naucalpan de Juárez: Pearson Educación.'),
	('Madrid: Síntesis'),
	('México: McGraw-Hill.'),
	('Ediciones SM Chile'),
	('Madrid: Pearson'),
	('México, Addison Wesley'),
	('Reading Mass: Addison-Wesley Iberoamericana.'),
	('Coprim'),
	('Santa Fe de Bogotá, Mc Graw-Hill.'),
	('Ministerio de educación'),
	('Kopetusz, Buenos Aires.'),
	('Santillana, Madrid.'),
	('Magisterio. Bogotá.'),
	('Editorial Verbo Divino : Navarra. España.'),
	('MacGraw Hill Book Co. New York.'),
	('Fondo de Cultura Econòmica'),
	('Ediciones Penìnsula'),
	('NARCEA S.A. DE Ediciones'),
	('Paidos Espasa Libros,S.L.U.'),
	('Editorial Siglo XXI'),
	('Editorial Siglo XXI, Buenos Aires.'),
	('Paidos'),
	('Siglo veintiuno editores'),
	('Losada'),
	('Centro Editor de Cultura'),
	('LOM Ediciones'),
	('Verbo Divino'),
	('C.P.U.'),
	('Fernández Editopress, S.A.'),
	('Fondo de cultura económica'),
	('Dolmen Ediciones'),
	('Colecciòn Austral'),
	('Fondo de Cultura Económica'),
	('Paidos, Buenos Aires'),
	('Siglo XXI Editores'),
	('Editorial Akal'),
	('Editorial Herder'),
	('Universidad Nacional Autónoma de México'),
	('Editorial Humanitas'),
	('Zigzag'),
	('Ariel'),
	('Siglo XXI'),
	('Dionysios'),
	(''),
	('Gradifco'),
	('Club de Lectores'),
	('Universitaria'),
	('Trillas'),
	('Brontes, S.L'),
	('Planeta,S.A.'),
	('Brontes'),
	('Catalonia Ltda'),
	('Parramón.'),
	('Barcelona: CEAC'),
	('Alianza.'),
	('Idea Books'),
	('Parramon'),
	('Magisterio del Río de la Plata'),
	('EUDEBA'),
	('Ceac'),
	('Aljibe'),
	('SM Chile'),
	('Addison Wesley'),
	('Síntesis'),
	('Pearson'),
	('Pirámides'),
	('Novedades Educativas.'),
	('Santiago: Universidad Católica de Chile'),
	('Cooperativa Editorial Magisterio  Bogotá.'),
	('Ecoe Ediciones  Bogotá'),
	('Editorial Sb, reimp. Argentina'),
	('Ediciones Mensajero : Universidad de Deusto, Bilbao'),
	('Paidos, buenos aires.'),
	('Coprim. Chile.'),
	('Ministerio de educación. Chile'),
	('Mediterráneo. Santiago, chile.'),
	('Edición Abierta, Santillana, Madrid.'),
	('Editorial Magisterio. Bogotá.'),
	('Santiago Chile: Universitaria'),
	('Santiago, Chile : Academia Chilena de Ciencias. Universitaria.'),
	('Madrid : Síntesis'),
	('Ediciones SM Chile. Santiago, Chile. 2014.'),
	('Mexico: Alfaomega.'),
	('Santiago, Chile : Universitaria'),
	('Madrid : La Muralla'),
	('Madrid : Narcea'),
	('Santiago, Chile: Ministerio de Educación.'),
	('La Rioja : Universidad Internacional de la Rioja'),
	('Buenos Aires: Paidós.'),
	('Madrid: Ediciones Pirámides'),
	('Santiago, Chile. Universitaria'),
	('México. Grijalbo'),
	('Visor, Madrid'),
	('Paidós, Barcelona.'),
	('Trillas; México.'),
	('Alianza, Madrid.'),
	('AIQUE, Buenos Aires.'),
	('AIQUE, Madrid.'),
	('Barcelona, Aprendizaje escolar y construcción del conocimiento.'),
	('Alianza'),
	('Kage Page, USA.'),
	('Mc Graw Hill, Mexico.'),
	('Fondo de cultura económica, México.'),
	('Siglo XXI de España; España.'),
	('México: International Thomson Edits.'),
	('McGraw-Hill, Mexico.'),
	('Madrid: International Thompson Editores.'),
	('Morata, Madrid.'),
	('Paidos, Barcelona.'),
	('Trans Lo Blanch; Valencia.'),
	('Magisterio, Colombia.'),
	('Narcea, Madrid.'),
	('Santiago de Chile: Ediciones Universidad Católica.'),
	('Barcelona: Grao'),
	('Madrid: Espasa Calpe.'),
	('Madrid: M. Fernández y Cía., S.A.'),
	('Santiago: Ministerio de Educación de Chile.'),
	('Madrid: M. Fernández y Cía., S.A'),
	('Santiago de Chile: Ediciones SM.'),
	('Santiago: Ediciones SM.'),
	('México: MCGraw-Hill.'),
	('Santiago de Chile: S.M. Ediciones.'),
	('SM Chile. Santiago, Chile.'),
	('Barcelona. Herder.'),
	('Universidad católica de Chile.'),
	('Narcea Ediciones.'),
	('Buenos Aires: Javier Vergara Editor'),
	('Barcelona: Grijalbo.'),
	('Ediciones Granica SA.'),
	('El Ateneo. Buenos Aires.'),
	('Universidad de Concepción. Chile.'),
	('La Muralla. Madrid'),
	('Aljibe. Málaga'),
	('Universidad Austral. Facultad de Filosofía y Humanidades. Chile.'),
	('Muñoz Moya y Montraveta editores de Colombia Ltda., Sevilla'),
	('Santiago, Chile. Zig-Zag'),
	('Chile. Ministerio de Educación'),
	('Chile. Coprim.'),
	('Bogota. Editorial magisterio.'),
	('Madrid: Pirámides.'),
	('Buenos Aires: Novedades Educativas.'),
	('Barcelona: Cultural.'),
	('México: Herrero hermanos sucesores'),
	('México: compañía editorial continental'),
	('México: McGraw Hill Iberoamericana'),
	('Buenos Aires: Bonum'),
	('McGraw-Hill, Interamericana Editores, S.A. México.'),
	('Madrid: Editorial médica Panamericana'),
	('Buenos Aires: Addison-Wesley Iberoamericana'),
	('La Serena: Ediciones Universidad de la Serena'),
	('Cooperativa Editorial Magisterio Bogotá.'),
	('Mensajero : Universidad de Deusto, Bilbao'),
	('Pirámide. Madrid.'),
	('La Muralla. Madrid.'),
	('Aljibe. Málaga.'),
	('Muñoz Moya y Montraveta editores de Colombia Ltda., Sevilla.'),
	('MAD, S.L. Alcalá de Guadaíra, Sevilla.'),
	('Ediciones Fondo Educativo Interamericano. México.'),
	('Editorial Paidós Ibérica'),
	('Editorial Andrés Bello. Chile.'),
	('España, siglo XXI'),
	('Barcelona: Graó.'),
	('Santiago: Dolmen Educación.'),
	('Santiago: Maval Limitada.'),
	('Siglo XXI, México.'),
	('Thompson – Paraninfo, Madrid.'),
	('Universidad Austral de Chile, Valdivia'),
	('Herder, Barcelona.'),
	('M. Fernández y Cía., S.A., Madrid.'),
	('Universitaria.'),
	('Planeta'),
	('Rosario: Homo Sapiens Ediciones'),
	('Madrid: Alianza.'),
	('Por Valles'),
	('Barcelona: Editorial Ariel. (Capítulo 1)'),
	('Buenos Aires: Edic. Siglo XX. Pág. 9-68.'),
	('Rosario: Homo Sapiens Ediciones.'),
	('México: Ediciones Aljibe, S. L. (Capítulo 2, 3 y 4)'),
	('España: McGraw-Hill'),
	('Madrid, España. Narcea'),
	('Espacio.'),
	('Pirámide'),
	('Alcalá de Guadaíra'),
	('Santiago, Chile: Ediciones UC.'),
	('Cooperativa Editorial Magisterio'),
	('Ecoe Ediciones'),
	('Ediciones Mensajero: Universidad de Deusto, Bilbao'),
	('El Ateneo'),
	('Universidad Austral'),
	('MAD, S.L. Alcalá de Guadaíra'),
	('Editorial Síntesis S.A, España.'),
	('Madrid: Ediciones Morata'),
	('Veracruz – México.'),
	('Madrid: Morata.'),
	('Mc Graw Hill Latinoamericana S.A.'),
	('McGraw-Hill Interamericana editores S. A.'),
	('Acción. Barcelona: Laertes.'),
	('Pearson Educación.'),
	('Ediciones Aljibe, S. L.'),
	('Editorial Universitaria.'),
	('España: Universidad de Sevilla.'),
	('Javier Vergara Editor. '),
	('Universidad de Sevilla.'),
	('Grao'),
	('Editorial Aique.'),
	('Editorial Universidad de La Serena.'),
	('Editorial Síntesis.'),
	('Editorial Pearson.'),
	('Editorial Trillas'),
	('Homo Sapiens Ediciones.'),
	('AKAL'),
	('Mérida, España.'),
	('Universidad de Concepción'),
	('La Muralla'),
	('Moratas.'),
	('Santiago de Chile: Andrés Bello'),
	('Madrid: Narcea.'),
	('Morata.'),
	('Madrid: Morata S.L.'),
	('Narcea.'),
	('Narcea'),
	('0.'),
	('McGraw-Hill'),
	('4'),
	('Prentice Hall.'),
	('Rentice Hall.'),
	('Madrid, La M'),
	('Paidós.'),
	('Graó.'),
	('Arco Libros.'),
	('Vox'),
	('LexisNexis.'),
	('Andrés Bello, Santiago.'),
	('Editorial Tecnos. Madrid.'),
	('Jurídica  de Chile'),
	('Lom. Santiago'),
	('Univ. Inter. SEK.'),
	('Jurídica'),
	('Jurídica de Chile'),
	('Marcial  Pons Ed. Jur.'),
	('Civit'),
	('Rialp'),
	('Mirbet'),
	('Temis'),
	('Gedisa.'),
	('Jurídica de Chile.'),
	('Femando Torres'),
	('Edeval'),
	('Instituto Internacional de Teología a Distancia'),
	('Gredos.'),
	('Thesis Doctoral. Universidad de Barcelona'),
	('Andrés Bello.'),
	('Palestra'),
	('Lom'),
	('Universidad Católica de Chile'),
	('LexisNexis'),
	('Cuadernos Universitarios: Serie de Manuales. UAB'),
	('Depalma'),
	('Universidad Católica de Chile.'),
	('MeGraw Hill'),
	('Me Graw Hill'),
	('Me Graw Hill.'),
	('Thompson  Reuters.'),
	('Librotecnia'),
	('Jurídica Chile'),
	('Thompson'),
	('Pearson Educación'),
	('IEI'),
	('Jurídica Chile.'),
	('Alfabeta'),
	('Ciudad  Argentina'),
	('Legal Publishing'),
	('Thomson Reuters'),
	('Cen. Est. Ramón  Aceres'),
	('Fondo  de cultura económica'),
	('Jurídica Congreso'),
	('Conosur'),
	('LIBROTECNIA.'),
	('ED.  UC. (T.  Ill)'),
	('U. TALCA'),
	('Metropolitana'),
	('Univ. Católica de la Stma. Concepción'),
	('Jurídica Conosur'),
	('Editorial Juridica de Chile'),
	('Imprenta Universitaria'),
	('Ediciones UC'),
	('B de F Montevideo- Buenos Aires.'),
	('Jurídica de Santiago.'),
	('Jurídica  de Chile.'),
	('Abeledo Perrot'),
	('Líbrotecnia'),
	('Thompson Reuters'),
	('Gedisa'),
	('CLACSO'),
	('Académica Española.'),
	('UNESCO'),
	('LegalPublishing'),
	('Thomson-Reuters'),
	('Abeledo Perrot.'),
	('El Jurista.'),
	('Abeledo-Perrot'),
	('Académica  Española.'),
	('CLACSO.'),
	('AbeledoPerrot'),
	('Thomsom Reuter'),
	('Thomson Reuter'),
	('Thomsom Reuters.'),
	('UC'),
	('Juridica de Chile '),
	('B de F.'),
	('Legal Publishing.'),
	('Lexis Nexis'),
	('CECOCH.'),
	('Librotecnia.'),
	('Thomsom Reuters'),
	('Thomson Reuters.'),
	('Distribuidora Forense'),
	('Gabriela Mistral'),
	('Universitarias de Valparaíso'),
	('Debate'),
	('Legal Publishin '),
	('EUNSA'),
	('DIDOT'),
	('ARA'),
	('Limusa'),
	('Norma'),
	('Jurídicas de Santiago'),
	('Lexis Nexis.'),
	('Porrúa'),
	('Astrea'),
	('Metropoiitana'),
	('INDE Publicaciones'),
	('Paidotribo'),
	('Kolima Books'),
	('Stadium Boocks'),
	('Vanceulen Editorial Deportiva'),
	('Mcgraw-Hill'),
	('La Muralla, S.A.'),
	('Editorial Mediterraneo España'),
	('Biblioteca Nueva'),
	('Editorial Eae'),
	('Editoria Inde'),
	('Editorial Académica Española'),
	('Edit INDE'),
	('Edit. Lumen'),
	('Edit. Bonum'),
	('Edit. Stadium'),
	('Edit. MINEDUC'),
	('Edit. Sol'),
	('Edit. Paidotribo'),
	('Escuela española'),
	('Editorial Lumen'),
	('Universidad de Playa Ancha'),
	('Digeder'),
	('Gymnos'),
	('Editorial INDE'),
	('Editorial Universidad Católica de Chile'),
	('Martínez Roca'),
	('Editorial Paidotribo'),
	('Editorial INDE publicaciones'),
	('Editorial Gymnos'),
	('Editorial INDE Publicaciones'),
	('Universidad de Atacama'),
	('Edit. DIGEDER'),
	('Edit. FIVB'),
	('Edit. Tutor. S.A.'),
	('Edit. COCH'),
	('Edit. Wanceulen'),
	('Edit. Gymnos'),
	('Edit. INDE'),
	('Edit. STADIUM'),
	('Edit. Doyma'),
	('Edit. Académica española'),
	('Edit. Universidad de Alcalá'),
	('Edit Paidos'),
	('Edit. Kinesis'),
	('Edit Gimnos'),
	('Edit. UACH'),
	('Editorial Cultural S.A.'),
	('Edit. Chiledeportes'),
	('Edit. Instituto Internacional del Saber'),
	('Dykinson'),
	('Paidós'),
	('INDE'),
	('MINEDUC'),
	('Ediciones UACH'),
	('Univ. Politécnica Madrid'),
	('Paidos Ibérica'),
	('Universidad de Alcalá España'),
	('Ministerio de Educación'),
	('Magisterio'),
	('Inde'),
	('Universidad de Alcalá, Servicio de Publicaciones'),
	('Thomson'),
	('Escuela Española'),
	('International Thomson.'),
	('Iberoamérica'),
	('Anaya Multimedia'),
	('Grami'),
	('McGraw-Hill, Interamericana de España'),
	('Paraninfo'),
	('Bellisco'),
	('Fundación Confemetal'),
	('Alfaomega colombiana'),
	('Prentice-Hall Hispanoamericana S.A.'),
	('Thomson-Paraninfo'),
	('UOC'),
	('Narcea Edición'),
	('Elsevier'),
	('Elservier Science'),
	('Harcourt'),
	('Pearson Prentice Hall'),
	('Mediterráneo'),
	('McGraw-Hill Interamericana'),
	('Instituto de Investigación Pedagógica USAT'),
	('Editorial Medica Panamericana'),
	('Pearson education'),
	('Walter Kluwer'),
	('Pearson Hall'),
	('Masson'),
	('Elsevier Science'),
	('Ediciones Díaz de Santos'),
	('RIL editores'),
	('REVERTE, S.A'),
	('ELSEVIER'),
	('MASSON'),
	('Wolters Kluwer Health España'),
	('McGraw- Hill'),
	('Tébar'),
	('Fondo Educativo Interamericano'),
	('Ediciones Omega'),
	('Editorial Panamericana'),
	('Manual Moderno'),
	('Elsevier-Saunders'),
	('Editorial Médica Panamericana'),
	('Médica Panamericana'),
	('Wolters Kluwer/Lippincott Williams & Wilkins'),
	('McGraw Hill'),
	('Herder'),
	('Thomson Paraninfo'),
	('Javier Vergara'),
	('Macmillan'),
	('Cambridge'),
	('RIL Editores'),
	('Universidad Anáhuac'),
	('Ediciones Universidad Católica de Chile'),
	('Elsevier Masson'),
	('Wolters Kluwer'),
	('Celsus'),
	('Harcourt-Brace'),
	('Omega'),
	('Blume'),
	('John Wiley & Sons'),
	('W.H. Freeman'),
	('Continental'),
	('Wiley-Blackwell'),
	('Interamericana'),
	('WCB'),
	('Cultura'),
	('Addison-Wesley Iberoamericana'),
	('Addison-Wesley'),
	('Hispano Americana'),
	('UTEA'),
	('McGraw-Hill Latinoamericano'),
	('Grupo Editorial Iberoamericana'),
	('W.H. Freeman and Company'),
	('Oxford University Press Harla'),
	('Addison-Wesley Longman'),
	('Compañía Editorial'),
	('Reverté'),
	('Universidad de Barcelona'),
	('CSIC'),
	('Springer'),
	('McGrawHill'),
	('Addison Wesley Longman'),
	('Morata'),
	('Longman'),
	('Academic Press'),
	('Blackwell Science'),
	('Editorial Universitaria de Buenos Aires'),
	('Prentice-Hall'),
	('International Thomson Editores'),
	('Cengage Learning'),
	('Alhambra Universidad'),
	('FEI'),
	('Genrinis'),
	('Wiley'),
	('Freeman'),
	('Springer-Verlag'),
	('MacGraw-Hill Book Company'),
	('Aguilar'),
	('The Geological Society of London'),
	('Butterworth-Heinemann'),
	('Consejo Superior de Investigaciones Científicas'),
	('Geol. J.'),
	('Unión Tipográfica Editorial Hispano Americana'),
	('Wiley and Blackwell'),
	('Springer-Verlag Berlin Heidelberg'),
	('Blackwell Scientific'),
	('Manson Publishing LTD'),
	('Blackwell Scientific Publications'),
	('Limusa-Wiley'),
	('Revista Galego-Portuguesa de Psicoloxía e Educación'),
	('Universidad Autónoma de Madrid'),
	('Editorial McGraw-Hill'),
	('Sin editorial'),
	('Books/Cole'),
	('Geological Society, London, Special Publications'),
	('Blackwell'),
	('Pearson Education'),
	('Chapman and Hall'),
	('John Wiley'),
	('Rueda'),
	('SEPM Short Course Number 3'),
	('Manson Publishing Ltd'),
	('Litoprint'),
	('Pearson, Prentice Hall'),
	('Arial'),
	('Editorial Ariel Geografía'),
	('Editorial Síntesis'),
	('Alianza Editorial'),
	('Harper and Row Publishers'),
	('Columbia University Press'),
	('Geological Society Publication'),
	('Geological Society Pub House'),
	('Origo Ediciones'),
	('Ediciones Universidad de Tarapacá'),
	('Mostoles'),
	('RIALP'),
	('SME Portcity Press'),
	('Elsevier Scientific Publishing Company'),
	('Instituto Geográfico Nacional'),
	('Carlos López Jimeno'),
	('Noriega Limusa'),
	('SCL'),
	('Stanford University Press'),
	('John Wiley and Sons'),
	('Harper & Row Publishers'),
	('Instituto Geológico y Minero de España'),
	('Origo'),
	('Institution of Mining and Metallurgy'),
	('Methuen'),
	('Siglo Veintiuno Editores'),
	('512.13S979'),
	('F.E.I'),
	('CECSA'),
	('516.33M854'),
	('512.13C182'),
	('Limusa – Wiley'),
	('Harla'),
	('Cecsa'),
	('Editorial Iberoamericana'),
	('Addison Wesley Iberoamericana'),
	('Uteha'),
	('Prentice Hall Hispanoamericana'),
	('Ed. Continental'),
	('Editorial Everest'),
	('Omega Ediciones'),
	('Prentice-Hall Iberia'),
	('Prentice-Hall Hispanoamericana'),
	('USA'),
	('México'),
	('Argentina'),
	('España'),
	('Fondo Editorial Interamericano'),
	('Serie Schaum'),
	('Editorial Limusa-Wiley'),
	('Sociedad Brasileira de Matemática'),
	('Editorial La Colina'),
	('Reverte Ediciones'),
	('Madrid Del Castillo'),
	('Grupo Editorial Iberoamérica'),
	('Gestión'),
	('Macmillan Publishing Company'),
	('CIMM'),
	('Gordon and Breach Science Publishers'),
	('Minería Chilena'),
	('Compañía Editorial Continental'),
	('Marcombo'),
	('Ediciones Golmen'),
	('Mundi Prensa'),
	('Agrícolas Española S.A.'),
	('Panorama Editorial'),
	('ARMCO-CHILE'),
	('Hachette'),
	('Editorial Universitaria'),
	('University of Illinois Press'),
	('The MIT Press'),
	('Imprenta y Litografía Universo'),
	('Editorial Jurídica'),
	('Albatros'),
	('Editoriales Jurídicas Europa-América'),
	('Grijley'),
	('Cambridge, Mass'),
	('Evolución'),
	('Anaya'),
	('Prentice Hall International'),
	('Soelco'),
	('Univ. de Concepción'),
	('N/A'),
	('Alianza Universidad Textos'),
	('Alianza Universidad'),
	('Editorial Andrés Bello'),
	('Universidad Católica'),
	('MIDEPLAN'),
	('Ediciones Dolmen'),
	('Editorial Mediterránea'),
	('McGraw-Hill, Schaum'),
	('Thomson Editores'),
	('Noyes Publications'),
	('Cambridge University'),
	('Editora Ana Navarro'),
	('Computer Science Press'),
	('Brooks/Cole Thomson Learning'),
	('Sams Publisher'),
	('Thompson Editores'),
	('Universidad Técnica del Estado'),
	('UTHEA'),
	('Departamento de Física, Universidad de Atacama'),
	('CECSA México'),
	('Facultad de Ciencias, Usach'),
	('Editorial Pirámide'),
	('McGraw-Hill Professional'),
	('CEKIT'),
	('Limusa Wiley'),
	('Editorial Aguilar'),
	('Thomson Brooks'),
	('McGraw-Hill/Interamericana de España'),
	('KRK Ediciones'),
	('Artes Gráficas Diego'),
	('Editorial Brujas'),
	('Editor Juan Carlos Martínez Coll'),
	('Editor Univ. J. Autónoma de Tabasco'),
	('Grupo Editorial Patria'),
	('Strategic Management Collection'),
	('Harvard Business Review'),
	('Harvard Business Press'),
	('O’Reilly'),
	('Grijalbo'),
	('Empresa Editora Macro'),
	('Andrés Bello'),
	('Andrés Calero'),
	('Octaedro'),
	('Ministerio de Educación, Chile'),
	('Kopetusz'),
	('Santillana'),
	('National Geographic Learning'),
	('Pearson Longman'),
	('British Council'),
	('Editorial Científica'),
	('Heinle & Heinle'),
	('Pearson Education Limited'),
	('Aarontype'),
	('Palgrave'),
	('Routledge'),
	('Yerevan University'),
	('Edinburgh University Press'),
	('Bolcsesz Konzorcium'),
	('Siglo Veintiuno'),
	('Ediciones Granica'),
	('Cuatro Vientos'),
	('Editorial desconocida'),
	('Macmillan Education'),
	('Editorial Magisterio'),
	('Editorial Ideas Propias'),
	('AIQUE'),
	('Visor'),
	('Kage Page'),
	('International Thomson Edits'),
	('International Thompson Editores'),
	('Trans Lo Blanch'),
	('Espasa'),
	('M. Fernández y Cía.'),
	('Ministerio de Educación de Chile'),
	('Random House'),
	('Rudolf Steiner'),
	('Annick Press Ltd.'),
	('Dial Books for Young Readers'),
	('Heinemann Educational Books, Ltd.'),
	('Edward Arnold Publisher Ltd.'),
	('Alianza Universitaria Textos'),
	('Diana'),
	('Novedades Educativas'),
	('División de Educación General'),
	('Capelusz'),
	('Holt, Rinehart and Winston'),
	('American'),
	('Harper and Row'),
	('W. W. Norton'),
	('Helbling Languages'),
	('Macmillan Heinemann English Language Teaching'),
	('Ediciones Internacionales Universitarias'),
	('Estudios Pedagógicos'),
	('Morata S.L.'),
	('Ediciones Aljibe'),
	('The Duskin Publishing Group'),
	('Cengage Learning - National Geographic Learning'),
	('MacMillan Press Ltd'),
	('Little, Brown and Company'),
	('Palgrave MacMillan'),
	('Commercial Colour Press'),
	('Bedford St. Martin’s'),
	('Longman Group Limited'),
	('Routledge Publishers'),
	('Ministerio de Educación Chile'),
	('Psykhe'),
	('Eudeba'),
	('Editorial Ariel'),
	('Editorial Paraninfo'),
	('Universidad Pública de Navarra'),
	('W. W. Norton & Company, Inc'),
	('Heinle & Heinle Publishers'),
	('Cambridge Teacher Training and Development'),
	('American Psychological Association'),
	('Cambridge UniversityPress'),
	('Edward Arnold Publisher Ltd'),
	('Panamericana'),
	('Reverté S.A.'),
	('Pearson Education México'),
	('Lippincott Williams & Wilkins'),
	('Prentice Hall Hispanoameric'),
	('Elsevier España'),
	('Ediciones Urano'),
	('El Manual'),
	('Churchill Livingstone/Elsevier'),
	('Guanabara Koogan'),
	('Autoedición'),
	('Editorial EOS'),
	('Mediterránea'),
	('Susaeta'),
	('Fondo de Educación Interamericano'),
	('Wadsworth Publishing Company'),
	('Facultad de Ciencias, USACH'),
	('La Colina'),
	('Editorial Madrid Del Castillo'),
	('Compañía Editorial Continental CECSA'),
	('Ed. Aguilar'),
	('McGraw-Hill México'),
	('Taylor & Francis'),
	('Reverté Ediciones'),
	('Centro de Investigación Minera y Metalúrgica'),
	('CYTED'),
	('SME Mineral Processing Handbook'),
	('SME Mineral Processing Handbook (Weiss, N. L., ed.), SME'),
	('UDA'),
	('SERNAGEOMIN'),
	('Agrícolas Española'),
	('AcoPaulista'),
	('AIME'),
	('Society of Mining Engineering'),
	('Pergamon Press'),
	('Science Publisher'),
	('Ellis Horwood'),
	('The Metallurgical Society of AIME'),
	('Instituto de Estudios de Administración Local'),
	('Labor'),
	('University of Concepción'),
	('Rocas y Minerales'),
	('Aco Paulista'),
	('Instituto de Ingenieros de Minas de Chile'),
	('Instituto Tecnológico GeoMinero de España'),
	('The Canadian Institute of Mining and Metallurgy'),
	('The Institute of Mining and Metallurgy'),
	('Centro Am.'),
	('Editorial Granica'),
	('CRC Press'),
	('SME'),
	('Oxford University Press-Harla México'),
	('W.H. Freeman y Company'),
	('Editorial Reverté'),
	('Editorial Continental'),
	('Ebook'),
	('Del Castillo'),
	('n.p.'),
	('Ed. del Castillo'),
	('Amorrortu Editores'),
	('Kapelusz'),
	('Instituto Tecnológico Geominero de España'),
	('Nora Boktryckeri'),
	('Gráfica Arias Montano S.A.'),
	('Gráficas Arias Montano S.A.'),
	('Prentice-Hall Hispanoamericana, S.A.'),
	('Universidad Politécnica de Madrid'),
	('CRC Press, Barcelona'),
	('CEMA'),
	('Universidad de Oriente'),
	('AusIMM'),
	('Ediciones Mundi Prensa'),
	('SME of AIME'),
	('AIMM'),
	('División el Teniente de Codelco Chile'),
	('Consejo Interamericano de Seguridad'),
	('Ed. Universitaria'),
	('Ed. Mostoles'),
	('Ediciones RIALP'),
	('Anales del congreso cincuentenario'),
	('Inst. Geográfico Nacional'),
	('Society for Mining, Metallurgy, and Exploration'),
	('Mining Journal Books'),
	('Taylor & Francis Group'),
	('Editorial Limusa'),
	('Burnaby British Columbia'),
	('Metallurgy Extractive'),
	('Universidad del Norte'),
	('Project Management Institute Inc.'),
	('Editorial Durán San Martín'),
	('Editorial Díaz de Santos'),
	('Western Mine Engineering Inc.'),
	('Society for Mining, Metallurgy, and Exploration Inc.'),
	('Díaz de Santos'),
	('Editorial Urano'),
	('Editorial Kairós'),
	('Saunders'),
	('El Manual Moderno'),
	('Harcourt Brace'),
	('Acribia'),
	('INTA'),
	('Interamericana-McGraw-Hill'),
	('Editorial de Argentina'),
	('Masson Salvat'),
	('Ergon'),
	('Universidad de Antioquia'),
	('Mediterraneo'),
	('Siglo Veinte'),
	('RI Editores'),
	('Editorial UC'),
	('Ediciones Panamericana'),
	('Tebar'),
	('Lippincott Williams'),
	('Lippincott Williams & Wilkins, Wolters Kluwer Health'),
	('Elsevier Mosby'),
	('Editorial PUC'),
	('McGraw Hill Interamericana'),
	('La Liebre de Marzo'),
	('Ediciones Universidad Católica'),
	('Mosby-Yearbook'),
	('Lippincott Williams and Wilkins, Wolters Kluwer Health'),
	('Lippincott Williams and Wilkins'),
	('DAE'),
	('Humanistas'),
	('Instituto de Terapia Cognitiva'),
	('Akal'),
	('Impresia Ibérica'),
	('Humanitas'),
	('Biblioteca Argentina de Filosofía'),
	('Graó'),
	('Visor Distribuciones'),
	('RAE'),
	('HomoSapiens'),
	('Alba Editorial'),
	('Rossa Sensat'),
	('Ediciones Octaedro'),
	('Opetusz'),
	('OPS'),
	('Biblioteca Nacional de Chile'),
	('Laertes'),
	('Cosades'),
	('Salvat'),
	('Cultural'),
	('NARCEA S.A. de Ediciones'),
	('Paidos Espasa Libros'),
	('Fernández Editopress'),
	('Ediciones del Serbal'),
	('Gobierno de Chile'),
	('Ediciones Narcea'),
	('Ediciones Morata'),
	('Universidad de Sevilla'),
	('Homo Sapiens Ediciones'),
	('Oceano'),
	('Universidad Central de Chile'),
	('Parramón'),
	('CEAC'),
	('Thompson – Paraninfo'),
	('Universidad Austral de Chile'),
	('CEC'),
	('Thomson Learning'),
	('Cepe'),
	('Espasa Calpe'),
	('Universidad de Alcalá'),
	('---'),
	('Pontificia Universidad Católica de Chile'),
	('Dasa'),
	('Mataquito'),
	('Evaluation and Program Planning'),
	('International Thomson'),
	('Siglo XXI de España'),
	('Rev Neurol'),
	('Vergara'),
	('Estudios Gráficos Europeos'),
	('Ograma Impresores'),
	('Paso de Gato'),
	('Titivilus'),
	('Universidad Católica del Norte'),
	('SECAB'),
	('Pearson Educación S.A.'),
	('Ediciones Morata, S.L.'),
	('Morata, S.L.'),
	('Pensamiento Educativo'),
	('Editorial Mataquito'),
	('Universidad Tecnológica Metropolitana'),
	('San Pablo'),
	('Edic. Siglo XX'),
	('9'),
	('Ediciones Fondo Educativo Interamericano'),
	('Editorial Cepe'),
	('Editorial Morata'),
	('Paidós Ibérica'),
	('Aguilar Chilena Ediciones'),
	('Ediciones B'),
	('Ediciones Vergara Grupo Zeta'),
	('Grupo Patria Cultural'),
	('CPEIP'),
	('Espacio'),
	('REICE'),
	('Junta de Andalucía'),
	('Editorial Salesiana'),
	('Fundación Mírame'),
	('Homo Sapiens'),
	('Octaedro, Rosa Sensat'),
	('HomoSapiens Ediciones'),
	('Editex S.A.'),
	('Mineduc'),
	('Barcelona'),
	('Santiago de Chile'),
	('División de Políticas Educativas'),
	('Ciencias de la Educación Preescolar y Especial'),
	('MacGraw-Hill Interamericana'),
	('Editorial Marfil'),
	('Mad'),
	('UNICEF'),
	('Editex'),
	('Universidad Católica Cardenal Raúl Silva Henríquez'),
	('Maval'),
	('Grupo Mayéutica Conpa'),
	('Pearson Educación, S.A.'),
	('Kart editores'),
	('Universidad de La Serena'),
	('Ediciones Nauta'),
	('Carrogio'),
	('Editorial Nascimiento'),
	('Vicens-Vives'),
	('Zig-Zag'),
	('Academia Boyacense de Historia'),
	('Popular'),
	('Universidad Católica Cardenal Raúl Silva Henríque'),
	('Complutense'),
	('Automind Educación'),
	('--'),
	('Editorial Gredas'),
	('Ediciones Cátedra'),
	('Ediciones Escritura Creativa Fuentetaja'),
	('Plot Ediciones S.A.'),
	('Editorial Anagrama'),
	('Editorial Paidós'),
	('Ediciones Robinbook'),
	('Homo sapiens Ediciones'),
	('Homo sapiens'),
	('Editorial Crítica'),
	('Ediciones Ceac'),
	('Lumen-Humanitas'),
	('CCS'),
	('Editorial CCS'),
	('Susaeta Ediciones'),
	('Educación y Sociedad'),
	('Ediciones de la JUNJI'),
	('PUC'),
	('Atenas Ltda.'),
	('Síntesis S.A'),
	('Veracruz – México'),
	('McGraw Hill Latinoamericana S.A.'),
	('Ediciones de la Biblioteca de la Universidad Central de Venezuela'),
	('Xudozhestvennaia Literatura'),
	('Edhasa'),
	('Nortwestern University Press'),
	('Anagrama'),
	('Editorial Debate'),
	('El Barquero'),
	('Editorial Visor'),
	('Paidós Ibérica S.A.'),
	('Penguin Random House Grupo Editorial'),
	('McGraw-Hill Interamericana de España'),
	('Tecnos'),
	('FC Editorial'),
	('Mc Graw-Hill'),
	('Tirant lo Blanch'),
	('Mc. Graw Hill'),
	('Dolmen ediciones'),
	('Bibliográfica Internacional'),
	('Lord Cochrane'),
	('Universidad Iberoamericana, Anthropos'),
	('Cátedra'),
	('McMillan'),
	('Pearson-Longman'),
	('Wiley Publishing'),
	('Ed. Trotta'),
	('Ed. Pearson'),
	('Ed. Universitas'),
	('Ed. Narcea'),
	('Antrophos'),
	('Paídos'),
	('Universidad de Valparaíso'),
	('LOM'),
	('Desclée de Brouwer'),
	('Mac-Graw-Hill'),
	('Santiago, Chile'),
	('Mc Graw Hill'),
	('Pretince Hall Hispano Americana S.A.'),
	('Mc.Graw Hill'),
	('Descleé'),
	('Manual moderno'),
	('Ercilla'),
	('Santiago Rueda Editores'),
	('Desclée De Brower'),
	('Amorrortu'),
	('Nómadas'),
	('Soc. de Cultura Valle-Inclán'),
	('Kairós'),
	('Índigo – Cuarto Propio'),
	('Ediciones La Llave'),
	('Cuatro Vientos Editorial'),
	('Mc-Graw-Hill'),
	('Centro de Estudios Ramón Areces'),
	('Prentice Hall Internacional'),
	('Aguilar Chilena de Ediciones'),
	('Desclée De Brouwer'),
	('Pax Mexico'),
	('Lumen'),
	('OPS/OMS'),
	('Distal'),
	('Ediciones Magisterio del Rio de La Plata'),
	('Nueva Visión'),
	('Klex'),
	('Ediciones Culturales Universitarias Argentina'),
	('JVE Psique'),
	('Lugar Editorial'),
	('Tea Ediciones'),
	('Gráfica Printer S.A.'),
	('Dwarf'),
	('ALBOR-COHS'),
	('Galdoc'),
	('Editorial Alianza'),
	('Ediciones Aljibe, S.L.'),
	('Sudamericana'),
	('Instituto colombiano para el fomento de la educación superior'),
	('Programa Interdisciplinario de Investigación en Educación, Academia de Humanismo Cristiano'),
	('Catalonia'),
	('Editorial Interamericana'),
	('Pretince Hall'),
	('Ariel Neurociencias'),
	('Edit. Manual Moderno'),
	('Siglo XX'),
	('Editorial El Manual Moderno'),
	('McGraw Hill Latinoamericana'),
	('Sexta edición'),
	('Editorial de los 4 Vientos'),
	('Editorial Síntesis S.A'),
	('Editorial Amerinda'),
	('Desclee De Brouwer'),
	('Trotta'),
	('ETrillas'),
	('Ed. Antrophos'),
	('Editorial Mc Graw Hill'),
	('Editorial Centro de Estudios Ramón Areces, S.A.'),
	('Prentice/Hall Internacional'),
	('Aguilar Chilena de Ediciones S.A.'),
	('Nancea'),
	('Praxis'),
	('Editorial Desclée de Brouwer'),
	('Grupo Edit. Iberoamérica'),
	('Coopecultura, Chile'),
	('Premium'),
	('McGraw-Hill Interamericana Editores'),
	('McGraw Hill/Interamericana Editores'),
	('Oxford University Press México'),
	('Thomson/South-West'),
	('Ediciones Jurídicas de Santiago'),
	('Fundación Juan March'),
	('McGraw-Hill/Interamericana Editores'),
	('PEARSON'),
	('Cono Sur, Chile'),
	('Consejo Económico y Social'),
	('Universidad Politécnica de Valencia'),
	('Alfaomega Grupo Editor'),
	('PEARSON Educación'),
	('Ed. Labor'),
	('Colección Tesis UDA'),
	('U.O. Proyectos, E.T.S.I. Minas, Universidad Politécnica de Madrid'),
	('Editorial Universidad de Atacama'),
	('Universidad de León'),
	('Gedisa Editorial'),
	('Ediciones Obelisco S.L.'),
	('Editorial Planeta'),
	('Editorial Cuatro Vientos'),
	('Editorial LOM'),
	('Editorial Biblioteca Nueva'),
	('Editorial Tirant Lo Blanch'),
	('ALAETS-CELATS'),
	('Los Andes'),
	('Ediciones Chile América CESOC'),
	('Secretaría de Comunicación y Cultura'),
	('Flacso'),
	('Universidad de Costa Rica'),
	('Editorial Espacio'),
	('Sot'),
	('Editorial Universidad Arcis'),
	('Editorial Biblos'),
	('Impresos y Revistas S.A.'),
	('Logman de México Editores'),
	('JC Sáez Ediciones'),
	('Editorial Manantial'),
	('Fondo de Cultura Económica de España'),
	('Anthropos'),
	('Espacio Editorial'),
	('Alfaomega Ra-Ma'),
	('Mac Graw Hill'),
	('Amarú'),
	('Muralla'),
	('Universidad de Deusto'),
	('McGraw-Hill/Interamericana'),
	('Internacional Thomson Editores'),
	('Ediciones Universitarias'),
	('PPC'),
	('Aguaclara'),
	('Macmillan Press'),
	('Ediciones Universidad Tecnológica Metropolitana'),
	('Plaza y Valdés'),
	('Ed. Síntesis'),
	('Ediciones LOM/Universidad ARCIS'),
	('FLACSO-Chile'),
	('Addison-Wesley Iberoamericana España'),
	('Plus Ultra'),
	('Comares'),
	('Editorial UOC'),
	('Cheriton House Publishing'),
	('Oberta'),
	('Universidad de Las Palmas'),
	('Ediciones Luna'),
	('M. Fernández y Cía. S.A.'),
	('Planeta Agostini'),
	('Aurea Hispánicos'),
	('Calpe'),
	('Gredos'),
	('Aslib'),
	('WBC Books'),
	('Ediciones SM'),
	('UACH'),
	('Arco/Libros'),
	('Instituto Cervantes-Aguilar'),
	('Centro de Investigación'),
	('Editorial Verbum'),
	('Multilingual Matters'),
	('Editorial Cátedra'),
	('John Benjamins Publishing Company'),
	('Facultad de Humanidades, Universidad Austral de Chile'),
	('Editorial Fundamentos'),
	('M. Fernández y Cía., S.A.'),
	('Universidad de Atacama, Copiapó'),
	('Ibérica'),
	('Georgetown University Press'),
	('Tecnológico de Monterrey'),
	('Editorial Forja'),
	('Sintesis Editorial'),
	('EU'),
	('SEP/Santillana'),
	('Editorial CEC, SA'),
	('Oficina de Traducciones del Gobierno de Canadá'),
	('The University of Michigan Press'),
	('Comercial Color Press'),
	('Pearson, Addison-Wesley'),
	('Documenta Universitaria'),
	('St. Jerome Publishing'),
	('Saint Jerome Publishing'),
	('Editorial Gredos, S.A.'),
	('Editorial Comares'),
	('Editorial Uoc, S.L.'),
	('Universidad de Santiago'),
	('Simon and Schuster'),
	('Stauffenburg Verlag'),
	('Anglo-Didacta Publishing'),
	('Atrio'),
	('SM'),
	('No editorial'),
	('Coopecultura'),
	('Cono Sur'),
	('Publiley'),
	('Horno Sapiens'),
	('Centro Interdisciplinario de Estudios en Bioética (CIEB), Vicerrectoría de Investigación y Desarrollo, Universidad de Chile'),
	('Granica'),
	('Irwin'),
	('Prentice'),
	('Narcea Ediciones'),
	('Enseñanza de las Ciencias'),
	('Boletín de la Asociación Provincial de Museos Locales de Córdoba'),
	('XIII Congreso Geol. Chileno'),
	('Ediciones Paraninfo, SA'),
	('Limusa: Wiley'),
	('Universidad de los Andes. Facultad de Ingeniería'),
	('Taller de Publicaciones de Ingeniería ULA'),
	('Estudios Geográficos'),
	('Enseñanza de las Ciencias de la Tierra'),
	('Gráficas Arias Montana'),
	('Ed Universitaria S.A.'),
	('EDUNI'),
	('COCHILCO'),
	('Servicio de Publicaciones del IGME'),
	('ITGE'),
	('Balkema'),
	('Ediciones Paraninfo, S.A.');